table PUERTO_ORIGEN
	lineageTag: 7e33a770-1f34-4bbc-8e91-9fc84886e913

	column Code
		dataType: string
		lineageTag: c631befe-9171-47fc-a3e3-a0cb0b5da08a
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column 'Port Name SAP'
		dataType: string
		lineageTag: 9baece0f-3f1c-4108-952c-82b52e3f72c2
		summarizeBy: none
		sourceColumn: Port Name SAP

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6d9ec322-f7a6-4edd-bc32-ecee023e90c8
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Name Country'
		dataType: string
		lineageTag: 815f771a-86cb-4549-ae36-252aa473eade
		summarizeBy: none
		sourceColumn: Name Country

		annotation SummarizationSetBy = Automatic

	column 'Tipo Linea'
		dataType: string
		lineageTag: 23dfa219-1cf1-421f-bc7e-b2956082ea74
		summarizeBy: none
		sourceColumn: Tipo Linea

		annotation SummarizationSetBy = Automatic

	partition PUERTO_ORIGEN = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nVpNe9u4Ef4rfHLe7GPoW0eQhERIJMGAgBwrzx64seqoK0upbKfdW+899SfscQ976NNbr/4n/SWdGdAJpcYE7ctk6X0HGGIG8/FSHz68iQ7Xmzc/vCkOx/sgr243QckLeI4OD/v746/wX/THb49m+/kQpNv9pnrz0w8f3lxcMPgjj/jCmpQHb4NyBc8kxC4oq92X6vpwhKe0X+N7iI8tz3kQidxonoJWpHFPEoe7+yrQ249VU6n/TankeRBybVSqumw3QM15rMpOxg0JbcE0nkqwToDS3MAfnXio7je31e7EtNF3VJIc/ujEYX/9cKzumhpj1Ehj0c2kCaIzXnA63vaVp4jN51ZyYzuszS4QXxSpMCoHvC3hmYQAJ1wf7gK73+I/15uA3z7+fjz1CiPXv+MhGrZQ8ODE4Xhd7beEHNdIdHrI01AhtOAYcCSqfXX7+Ftzzb5DGgnALIYHJw676+rL9mT3ASHz+VItAWsSDE4S1XZX7a9PDRjW4JTDuSeAD3FZJ6r9za663tx9aiqMSEFHIlU5Gi3oWNzZfK4e/3ViCno0VB09ytCjoY0SrkVpQEHjqTnxcFvtH/84WXtKaJHzFQSX1bhDhFgnDrvD7c8n59K7IAW8JgBd4p1auot13FTgSbDp4dh40x4jb5QKAjhXvPQ4qIeujHgo1mhJLjFDkIDYOFY3Dyem9AkLoe7Mbr/kvQGh9ZwHXGjRYfmhUzB8LnL/uaBHIxHixSgwTkjMtrvt5+3eXaOnE0F3RonIc45RKPG2OXEWVb0JAaUBC1Q+90dVb+oULjletwjXdOITmNDA9dGHkbQxj4NYBJBdjMhcAmjPRn1GJ5CqLMTsmC7x/6Eoj9sgrfa/nOzSq8G5x+d98qNCC4ouEd4nTyotc6O8XuyTF7UsjQqpFrRaQk60kTVef/fJi9bYqEud6KMrY8jgPs+gB2Ox4r57O0AXijSA1G1kSrWqNXcP2P/hfTYPek4lTO1s5j3nQd+h4cJkIvdG0mBwBs/eYx4m8fj737YfD03wsAYLSXHnWXp0im5deVxjv0ZT+ylOHFyUhcz9sTeYOvgsheVjv+XDi3N8qzXD2qeQSkREgdUOr/1ZqCsvtN+E+gJlWPtSQ3B5z2RIvsxLSKkx93hnSJ6EJk4EWqrSf37ozZldJ8q23rIhuhGSuqJ7JnE5J+6r3cklH6IDIT3CzeULrn32ji4cPId2lRtf7I1YjYb2kbL78waPek9Q77uN+g5acpt6e8XR4BTc7roRui7hckanluKBkbg7Vptd04SRwxWJe68V7u7EdnMPObeJHRM2C62e44HFghIgCL4D9+5P3DFCvyXQSSQyyGSe+NaeEhxsWPoOeIyeS/CAi/bjHTN6bVUAtEsSHaPnZA4eFqWkc8Pq7cT++rDf3J2U/HGf4OQSb7iP0XtQ2HgeWqxsBnsfJx6Of3k4LRhjdB7E8BIbGr8dI0JfcugiUyibuUi0bW1WxujIhdIxJaKW6BijE+F+5DhqgSkZ17JD+zZGZy65SkppyZnmEl+URLX96+Nv+8YekwsCa46RAiUfWxQnql+2d/dnYHTpUojUeoJkgr5cqkisFnhZSrwnJMTd7vBlcxqrE/QktFQ8F+8ltUCeF5wMagWrlfY7fzJ0cKxy3sltMnJgoTNpOqw9dvCZhsZQ5xL7RN8OE6eSwJHDJK279HGTqdPJ4GqkqS+5Ti8c2ubuOH2rTxnhRQbpguNs5p3ipj3SKDG/5FDLyi679GudDKab0ndK08EZuj3hTp2P11zj9KRjqJml75TI0yIrpPZGxZTcLKloF5hyndgcH//TRE0cqksMT8mjcqU0dUfPV1Z2Qd6EMwDHiFSURG/MQI9ywcuYAkYkERwp8SSeQ2XEEAFYUsS1jmqMiCHAGkhXvhcaOOgaV049tZ8RE5SJWKSpzD2jBiMOKBNplCiN8xo0zJG/G2JEBGWQfWBCiWc+g9DLmeSZDOr28zV+mNIicH3m/OWEDyO+COIM+j3H2uGQ5gRMatfNSY0ROZTZLGyfoRlRQ7m4DBZCl+LqFUb16wWulF6+Qh3DIk84dJpl4ua6FmOHFLj5nOaWZwsRI/ZI8WXK8/gVJmFcqEJp6lALDB8nDsf7h5tq14RiVKiSz0UQvOZiErt0Sv60ZxBG9FIhYsh4EOk8XUER909OzLFM4vGfsEcIxxJ12qv3PaX27EGcU5HIVBYwAorSm0KIdiqSXGWQY6llXSKURFTd/nz4telZ4pwKZVQp/aZgFBRWhL7SyYhxAiR6POS6yyzFiHxq6HRTmn5T6krMMWKjnpQgKsXaU7gY0VC1BkRJyrWgGHlhdBJBVS+TCuVhIRjRVE/wTvWQEVNVq7yzwqwpr7WfIRFW7yAJxLw9CxBZBTM3GLKCkiMgY2fQOabC14Yw4q7AocFcQwbBXjbEV3ACoNtmDiDqSituvAwDI/YKmWFoVlJ/f8OIxCJ8g59rPx3isc5VPE0aIyYLlWIpYGoTwtqXRwsRXN8Wyd57woUYLsQvVAnpEyo2dN5aRh1uBPFdqOoSYWm932YYkV4lDVWQM2NoFDocy9jpxB24LEbU10smNjaoo8GIYCaCstAQ0+XLz31YBwlcIaOwKYeAhUxt6pGhPVyG7Em5bI9yIsdKAa/mJoXW8ZgRP1YmAE2o/3j+khI3hkjTztsw4sWgRcjXiWjliBmxYqUMpfWQxIz4sFLC7souKUd4yg8RYyX4iReWImiOzyS2+5vqc/PLDiNyrIRRL+RXXkaBETdmuMSexUXPsy9IxBhA3WeMljmfES9mOEw7ka/jJl7MiMjmgYU2PZDe2CFy7EyjdYfhGb7DFqPvqLTuMSaFuY2gxU4Lb1ogxswg77+Sq1ZehhFbBlDvmsSVGcnzhedrBiOyzMhlh7xOPJlRkXVfA1o+0jDiyIyCGSg30luTiCQzWl2GMNPM6YN7iDaEFKc3OzDleDyxhNyo7aLDZxVGPJmxRkZWky3PN/dEkK04XsLcipW/pyWibAUtVKTt2hMXxI6tpDA5z1pdQszYJWYZTz4iVuw9DISebESk2BXkN18wECG2ngVfS6K/QBElhipQdOCWdPkBCCNebI0f1WcaW/og/TH9sYseevK/f/9HbHXI364x9EiUDzB4/umsJhFBBu98KXTxto2yZsSLrTkSaW85Vh4njjeb/X19Pk/IqYuPAsCyVG8jvKVOfNruNg0kMWEdOXNGNJiAMHK/TXh5/SVWDM9yObPaeLdDL0Nsla/5yQcjfuxKLVXiPiUt8LdCTlSfH//dTP3Ejc0tlJ53VmJ+ERHuQuLjw5lzp/WoVA8MPIWaIX2fcxjxY4ngJoH04U8cRJRF4BblClxboSWirP4Cn8iYp3NP/epduKy7oB8peaCM7NaZKv1UVM/9YiorjdAxJY8cY45EUT3+cbe5C8Lqz4e7pgp9Y4p5Xi7xRyAFYUkcdoeTeOgRLTaPr5DX80GJ/YBFE4I+m0l6xIdFyO6rFJGJeRbZGHyx/4xkITwa9IUXEk7W+KbyfeRTeyv5nKIqSiTkdndjv6fgfg4ltPoWiDiD5WKu1VcK8Fzxp/8B", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Code = _t, #"Port Name " = _t, #"Country Code" = _t, #"Country Name " = _t, #"Tipo Linea " = _t]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true])
				in
				    #"Encabezados promovidos"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

