table EKPO_CD-TIENDA
	lineageTag: 17069062-e538-4ba3-97d3-36e35a95d107

	column DOCUMENTO
		dataType: string
		lineageTag: 762a0949-9cd9-4bea-9777-859145c0b262
		summarizeBy: none
		sourceColumn: DOCUMENTO

		annotation SummarizationSetBy = Automatic

	column ARTICULO
		dataType: string
		lineageTag: 899f558a-2bbb-4dbd-96f2-089718ecfbd8
		summarizeBy: none
		sourceColumn: ARTICULO

		annotation SummarizationSetBy = Automatic

	column Diferencia_Dias = ```
			
			VAR HoraCorte = TIME(12, 0, 0)
			VAR FechaCompra = 'EKPO_CD-TIENDA'[FECHA_DOCUMENTO_COMPRA]
			VAR FechaMaterial = 'EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL]
			VAR HoraCreacion = 'EKPO_CD-TIENDA'[HORA_CREACION]
			VAR ClaseDoc = 'EKPO_CD-TIENDA'[CLASE_DE_DOCUMENTO]
			VAR FechaAjustada = 
			    IF(HoraCreacion >= HoraCorte, FechaCompra + 1, FechaCompra)
			VAR FechaLiquidacion = 'EKPO_CD-TIENDA'[Liquidacion]
			
			RETURN
			    IF(
			        ClaseDoc = "ZTR2",
			        DATEDIFF(FechaLiquidacion, FechaMaterial, DAY),  -- ¡invertido aquí!
			        DATEDIFF(FechaAjustada, FechaMaterial, DAY)
			    )
			```
		formatString: 0
		lineageTag: a91f907d-a68c-4e8c-a07a-379b672735b1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MES = MONTH('EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL])
		formatString: 0
		lineageTag: 046c9a0c-4a45-4141-926f-00db104b97a1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SLA = 4
		formatString: 0
		lineageTag: 45b01316-c72b-4413-a83a-5296801f0789
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column CLASE_DE_DOCUMENTO
		dataType: string
		lineageTag: 1390380b-3854-456b-8352-531100aea7f5
		summarizeBy: none
		sourceColumn: CLASE_DE_DOCUMENTO

		annotation SummarizationSetBy = Automatic

	column FECHA_CREACION_REGISTRO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0f7f1ba1-c924-49ce-984f-b2ada71d80b4
		summarizeBy: none
		sourceColumn: FECHA_CREACION_REGISTRO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GRUPO_DE_COMPRAS
		dataType: string
		lineageTag: a8e7416f-c556-4e97-a6bf-4a14e6c2115a
		summarizeBy: none
		sourceColumn: GRUPO_DE_COMPRAS

		annotation SummarizationSetBy = Automatic

	column FECHA_DOCUMENTO_COMPRA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 41191688-942e-4113-a858-79327e769c74
		summarizeBy: none
		sourceColumn: FECHA_DOCUMENTO_COMPRA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CENTRO_SUMINISTRADOR
		dataType: string
		lineageTag: 0336e24e-2dbc-446b-ae4e-d81e311833c1
		summarizeBy: none
		sourceColumn: CENTRO_SUMINISTRADOR

		annotation SummarizationSetBy = Automatic

	column FECHA_TIENDA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 97dd1030-2743-4459-8498-d93bb972f800
		summarizeBy: none
		sourceColumn: FECHA_TIENDA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column POSICION_DOCUMENTO
		dataType: string
		lineageTag: 34cd7ad5-b400-4d7a-8bf1-9bfc4799fa53
		summarizeBy: none
		sourceColumn: POSICION_DOCUMENTO

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION
		dataType: string
		lineageTag: 70d56df3-502d-4d3e-8213-5a1f0c9a7571
		summarizeBy: none
		sourceColumn: DESCRIPCION

		annotation SummarizationSetBy = Automatic

	column CENTRO_DESTINO
		dataType: string
		lineageTag: 1695731a-38db-47dd-a5a2-b6242c32d5c7
		summarizeBy: none
		sourceColumn: CENTRO_DESTINO

		annotation SummarizationSetBy = Automatic

	column ALMACEN
		dataType: string
		lineageTag: 13034d6b-a0be-4f5a-b061-eeb322dc7c98
		summarizeBy: none
		sourceColumn: ALMACEN

		annotation SummarizationSetBy = Automatic

	column GRUPO_ARTICULOS
		dataType: string
		lineageTag: 762bdbee-983f-4a99-899f-c22f994b3fb2
		summarizeBy: none
		sourceColumn: GRUPO_ARTICULOS

		annotation SummarizationSetBy = Automatic

	column CANTIDAD_PEDIDO
		dataType: double
		lineageTag: 9a32fbd1-aa24-4e83-8d4c-59246eae7999
		summarizeBy: sum
		sourceColumn: CANTIDAD_PEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNIDAD_MEDIDA
		dataType: string
		lineageTag: ee4d430f-2b45-4e5f-99bc-7dd092b32517
		summarizeBy: none
		sourceColumn: UNIDAD_MEDIDA

		annotation SummarizationSetBy = Automatic

	column INDICADOR_ENTREGA_FINAL
		dataType: string
		lineageTag: 5755232a-36d4-4be7-a77c-2aa38f492fcf
		summarizeBy: none
		sourceColumn: INDICADOR_ENTREGA_FINAL

		annotation SummarizationSetBy = Automatic

	column EAN11
		dataType: string
		lineageTag: 63d5f8d7-ec16-4cfb-acd3-5285ebfd3164
		summarizeBy: none
		sourceColumn: EAN11

		annotation SummarizationSetBy = Automatic

	column ARTICULO_GENERICO
		dataType: string
		lineageTag: a50a877b-44d6-4376-8d71-67b243a8ab50
		summarizeBy: none
		sourceColumn: ARTICULO_GENERICO

		annotation SummarizationSetBy = Automatic

	column TIPO_MATERIAL
		dataType: string
		lineageTag: 9a40da3d-0ae4-4b72-a20b-3c7860725392
		summarizeBy: none
		sourceColumn: TIPO_MATERIAL

		annotation SummarizationSetBy = Automatic

	column ALMACEN_EMISOR
		dataType: string
		lineageTag: 1c953f59-cddb-4e2c-a905-e9aa93eafa3d
		summarizeBy: none
		sourceColumn: ALMACEN_EMISOR

		annotation SummarizationSetBy = Automatic

	column NUMERO_DOCUMENTO_MATERIAL
		dataType: string
		lineageTag: 2e5b49c3-d98f-44a6-85ec-5a327ccc01f7
		summarizeBy: none
		sourceColumn: NUMERO_DOCUMENTO_MATERIAL

		annotation SummarizationSetBy = Automatic

	column TIPO_MOVIMIENTO
		dataType: string
		lineageTag: 2e0986ae-5acb-47af-a74c-82b0237f782f
		summarizeBy: none
		sourceColumn: TIPO_MOVIMIENTO

		annotation SummarizationSetBy = Automatic

	column CANTIDAD_MOVIMIENTO
		dataType: double
		lineageTag: 9ace832c-e7ec-4912-9cf6-835a08144a85
		summarizeBy: sum
		sourceColumn: CANTIDAD_MOVIMIENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FECHA_DOCUMENTO_MATERIAL
		dataType: dateTime
		formatString: Short Date
		lineageTag: fc1538b0-21a1-4a78-a76f-3a61c4a5fa0c
		summarizeBy: none
		sourceColumn: FECHA_DOCUMENTO_MATERIAL

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIA_INGRESO_DOCUMENTO
		dataType: dateTime
		formatString: Short Date
		lineageTag: dbfab46f-d276-4388-ad4b-34689cdd4288
		summarizeBy: none
		sourceColumn: DIA_INGRESO_DOCUMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HORA_INGRESO_DOCUMENTO
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6a244a53-c9b9-4669-a367-01c3a3a19174
		summarizeBy: none
		sourceColumn: HORA_INGRESO_DOCUMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Año = YEAR('EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL])
		formatString: 0
		lineageTag: 4815c898-1ace-4609-96c4-a75db295a542
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column PAIS
		dataType: string
		lineageTag: 5e4c018b-a512-44be-97e0-91d1de334441
		summarizeBy: none
		sourceColumn: PAIS

		annotation SummarizationSetBy = Automatic

	column Estado_Documento = ```
			
			IF (
			    NOT ISBLANK('EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL]) && 
			    'EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL] <= TODAY(),
			    "Entregado",
			    IF (
			        ISBLANK('EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL]) &&
			        'EKPO_CD-TIENDA'[INDICADOR_ENTREGA_FINAL] = "X",
			        "Entregado",
			        "Pendiente"
			    )
			)
			```
		lineageTag: 24989afd-756d-44ff-a689-e20781b56b04
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CONTENEDOR_REFERENCIA
		dataType: string
		lineageTag: 62e6db76-2c1d-4988-94ce-5d57f3e0219d
		summarizeBy: none
		sourceColumn: CONTENEDOR_REFERENCIA

		annotation SummarizationSetBy = Automatic

	column HORA_CREACION
		dataType: dateTime
		formatString: Long Time
		lineageTag: d9effcb2-d47e-49db-8d3a-b86fe656a76d
		summarizeBy: none
		sourceColumn: HORA_CREACION

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Liquidacion =
			
			CALCULATE(
			    FIRSTNONBLANK('EKPO_BFI-CD'[FECHA_LIQUIDACION],1),
			    FILTER(
			        ALL('EKPO_BFI-CD'),
			        'EKPO_BFI-CD'[CONTENEDOR] = 'EKPO_CD-TIENDA'[CONTENEDOR_REFERENCIA]))
		formatString: Short Date
		lineageTag: cadd713f-709d-4b73-b31d-1aaf9b0805e9
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Semana = WEEKNUM('EKPO_CD-TIENDA'[FECHA_DOCUMENTO_MATERIAL])
		formatString: 0
		lineageTag: d5d44fd9-9532-479e-80fe-861b0ace65d4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FECHA_LIQUIDACION
		dataType: string
		lineageTag: ce12089c-5c5c-4ce2-9477-96a2c639f2df
		summarizeBy: none
		sourceColumn: FECHA_LIQUIDACION

		annotation SummarizationSetBy = Automatic

	column PE_MARA
		dataType: string
		lineageTag: 336c2bea-e650-47dc-a182-15723329fd26
		summarizeBy: none
		sourceColumn: PE_MARA

		annotation SummarizationSetBy = Automatic

	column PE_ANO_MARA
		dataType: string
		lineageTag: b7920745-c55f-42eb-9a2f-0458e304d2c7
		summarizeBy: none
		sourceColumn: PE_ANO_MARA

		annotation SummarizationSetBy = Automatic

	column PE
		dataType: string
		lineageTag: f1b7c729-d290-4581-8082-4a41fcad8e93
		summarizeBy: none
		sourceColumn: PE

		annotation SummarizationSetBy = Automatic

	column ANO_PE
		dataType: string
		lineageTag: 94eb39ee-1208-4900-8627-d06c75926aad
		summarizeBy: none
		sourceColumn: ANO_PE

		annotation SummarizationSetBy = Automatic

	column ESTILO
		dataType: string
		lineageTag: 6ad43cd8-f66a-40af-9c7c-c86d2f8d595e
		summarizeBy: none
		sourceColumn: ESTILO

		annotation SummarizationSetBy = Automatic

	column COLOR
		dataType: string
		lineageTag: a34d7a7b-a87c-40f4-aca4-f49a8d2b24f8
		summarizeBy: none
		sourceColumn: COLOR

		annotation SummarizationSetBy = Automatic

	column MARCA
		dataType: string
		lineageTag: 9dd26513-1565-46aa-898e-be97a027a09e
		summarizeBy: none
		sourceColumn: MARCA

		annotation SummarizationSetBy = Automatic

	column GENERO
		dataType: string
		lineageTag: f5859383-7463-41cd-b60c-848068982feb
		summarizeBy: none
		sourceColumn: GENERO

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: 2db445d3-305b-4c7d-8c4a-673021eb6c2e
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column Articulo_GenericoF = ```
			
			VAR Posicion = SEARCH("0000000", 'EKPO_CD-TIENDA'[ARTICULO], 1, -1)
			RETURN 
			IF(Posicion = -1, 
			    BLANK(), 
			    MID('EKPO_CD-TIENDA'[ARTICULO], Posicion + 7, 8)
			)
			```
		lineageTag: d4b585d3-6a0c-4082-b857-6024f609b862
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition EKPO_CD-TIENDA = m
		mode: import
		source =
				let
				    Consulta1 = Value.NativeQuery(SapHana.Database("vhadoahpdb01.hec.empresasadoc.com:30215", [Implementation="2.0"]), "WITH #(lf)-- CTE para cabecera de pedido#(lf)CabeceraCompra AS (#(lf)    SELECT#(lf)        EBELN AS Documento,#(lf)        LANDS AS Pais,#(lf)        BSART AS Clase_De_Documento,#(lf)        AEDAT AS Fecha_Creacion_Registro,#(lf)        EKGRP AS Grupo_De_Compras,#(lf)        BEDAT AS Fecha_Documento_Compra,#(lf)        RESWK AS Centro_Suministrador,#(lf)        ZZF_DESPACHO AS Fecha_Tienda,#(lf)        UNSEZ AS Contenedor_Referencia#(lf)    FROM SAP_ECC.EKKO#(lf)    WHERE BSART IN ('UB', 'ZTR2', 'ZREP')#(lf)    AND BEDAT >= '2024-01-01'#(lf)),#(lf)-- CTE para posiciones de pedido con joins a MARA#(lf)PosicionesCompra AS (#(lf)    SELECT#(lf)        EKPO.EBELN AS Documento,#(lf)        EKPO.CREATIONTIME AS Hora_Creacion,#(lf)        EKPO.EBELP AS Posicion_Documento,#(lf)        EKPO.TXZ01 AS Descripcion,#(lf)        EKPO.MATNR AS Articulo,#(lf)        EKPO.WERKS AS Centro_Destino,#(lf)        EKPO.LGORT AS Almacen,#(lf)        EKPO.MATKL AS Grupo_Articulos,#(lf)        EKPO.MENGE AS Cantidad,#(lf)        EKPO.MEINS AS Unidad_Medida,#(lf)        EKPO.ELIKZ AS Indicador_Entrega_Final,#(lf)        EKPO.EAN11 AS EAN11,#(lf)        EKPO.SATNR AS Articulo_Generico,#(lf)        EKPO.MTART AS Tipo_Material,#(lf)        EKPO.RESLO AS Almacen_Emisor,#(lf)        EKPO.FECHA_LIQ AS Fecha_Liquidacion,#(lf)#(lf)        -- Nuevos campos desde MARA y EKPO#(lf)        MARA.SAISO AS PE_MARA,#(lf)        MARA.SAISJ AS PE_ANO_MARA,#(lf)        MARA.GROES AS Estilo,#(lf)        MARA.FREE_CHAR AS Color,#(lf)        MARA.BRAND_ID AS Marca,#(lf)        MARA.ZZ_ART_PROV AS Genero,#(lf)        MARA.ZZ_DEPART AS Departamento,#(lf)        EKPO.SAISO AS PE,#(lf)        EKPO.SAISJ AS Ano_PE#(lf)#(lf)    FROM SAP_ECC.EKPO#(lf)    LEFT JOIN SAP_ECC.MARA ON EKPO.MATNR = MARA.MATNR#(lf)    WHERE EKPO.EBELN IN (#(lf)        SELECT EBELN#(lf)        FROM SAP_ECC.EKKO#(lf)        WHERE BSART IN ('UB', 'ZTR2', 'ZREP')#(lf)        AND BEDAT >= '2024-01-01'#(lf)    )#(lf)    AND EKPO.LOEKZ <> 'L'#(lf)),#(lf)-- CTE para movimientos de material#(lf)MovimientosMaterial AS (#(lf)    SELECT#(lf)        MBLNR AS Numero_Documento_Material,#(lf)        BWART AS Tipo_Movimiento,#(lf)        WERKS AS Centro_Destino,#(lf)        LGORT AS Almacen,#(lf)        MENGE AS Cantidad,#(lf)        MEINS AS Unidad_Medida,#(lf)        EBELN AS Documento,#(lf)        EBELP AS Posicion_Documento,#(lf)        ELIKZ AS Indicador_Entrega_Final,#(lf)        BUDAT_MKPF AS Fecha_Documento_Material,#(lf)        CPUDT_MKPF AS Dia_Ingreso_Documento,#(lf)        CPUTM_MKPF AS Hora_Ingreso_Documento#(lf)    FROM SAP_ECC.MSEG#(lf)    WHERE EBELN IN (#(lf)        SELECT EBELN#(lf)        FROM SAP_ECC.EKKO#(lf)        WHERE BSART IN ('UB', 'ZTR2', 'ZREP')#(lf)        AND BEDAT >= '2024-01-01'#(lf)    )#(lf)    AND BWART = '101'#(lf))#(lf)#(lf)-- Consulta principal#(lf)SELECT#(lf)    c.Documento,#(lf)    c.Pais,#(lf)    c.Clase_De_Documento,#(lf)    c.Fecha_Creacion_Registro,#(lf)    c.Grupo_De_Compras,#(lf)    c.Fecha_Documento_Compra,#(lf)    c.Centro_Suministrador,#(lf)    c.Fecha_Tienda,#(lf)    c.Contenedor_Referencia,#(lf)    p.Posicion_Documento,#(lf)    p.Hora_Creacion,#(lf)    p.Descripcion,#(lf)    p.Articulo,#(lf)    p.Centro_Destino,#(lf)    p.Almacen,#(lf)    p.Grupo_Articulos,#(lf)    p.Cantidad AS Cantidad_Pedido,#(lf)    p.Unidad_Medida,#(lf)    p.Indicador_Entrega_Final,#(lf)    p.EAN11,#(lf)    p.Articulo_Generico,#(lf)    p.Tipo_Material,#(lf)    p.Almacen_Emisor,#(lf)    p.Fecha_Liquidacion,#(lf)    p.PE_MARA,#(lf)    p.PE_ANO_MARA,#(lf)    p.Estilo,#(lf)    p.Color,#(lf)    p.Marca,#(lf)    p.Genero,#(lf)    p.Departamento,#(lf)    p.PE,#(lf)    p.Ano_PE,#(lf)    m.Numero_Documento_Material,#(lf)    m.Tipo_Movimiento,#(lf)    m.Cantidad AS Cantidad_Movimiento,#(lf)    m.Fecha_Documento_Material,#(lf)    m.Dia_Ingreso_Documento,#(lf)    m.Hora_Ingreso_Documento#(lf)#(lf)FROM CabeceraCompra c#(lf)LEFT JOIN PosicionesCompra p #(lf)    ON c.Documento = p.Documento#(lf)LEFT JOIN MovimientosMaterial m #(lf)    ON p.Documento = m.Documento #(lf)   AND p.Posicion_Documento = m.Posicion_Documento#(lf)WHERE (m.Centro_Destino = p.Centro_Destino OR m.Centro_Destino IS NULL)#(lf)  AND (m.Almacen = p.Almacen OR m.Almacen IS NULL)#(lf)ORDER BY p.Posicion_Documento, m.Fecha_Documento_Material", null, [EnableFolding=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Consulta1,{{"FECHA_CREACION_REGISTRO", type date}, {"FECHA_DOCUMENTO_COMPRA", type date}, {"FECHA_TIENDA", type date}, {"HORA_INGRESO_DOCUMENTO", type time}, {"DIA_INGRESO_DOCUMENTO", type date}, {"FECHA_DOCUMENTO_MATERIAL", type date}, {"HORA_CREACION", type time}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

