table 'EKPO L1 V2'
	lineageTag: a1db1e76-3f00-4839-94bb-ae76fdce80de

	column ARTICULO
		dataType: string
		lineageTag: 16fba2f7-ec25-4a70-b1e7-59711c7ab36d
		summarizeBy: none
		sourceColumn: ARTICULO

		annotation SummarizationSetBy = Automatic

	column ALMACEN
		dataType: string
		lineageTag: e0718c48-beef-472d-b7f4-d99ddb6a7e41
		summarizeBy: none
		sourceColumn: ALMACEN

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION
		dataType: string
		lineageTag: e465e69e-2439-4a2b-8760-7ed811a2c762
		summarizeBy: none
		sourceColumn: DESCRIPCION

		annotation SummarizationSetBy = Automatic

	column DOCUMENTO
		dataType: string
		lineageTag: fbedc9b3-ab03-4b63-a88a-16f5e3dcf231
		summarizeBy: none
		sourceColumn: DOCUMENTO

		annotation SummarizationSetBy = Automatic

	column PE
		dataType: string
		lineageTag: 3fbf6bf6-21da-4007-9618-46e089289c66
		summarizeBy: none
		sourceColumn: PE

		annotation SummarizationSetBy = Automatic

	column ESTILO
		dataType: string
		lineageTag: e9d25758-a4d7-4c35-a506-c86c80ce8923
		summarizeBy: none
		sourceColumn: ESTILO

		annotation SummarizationSetBy = Automatic

	column COLOR
		dataType: string
		lineageTag: ace8d4a0-9ccb-49d5-8efc-41105f51922f
		summarizeBy: none
		sourceColumn: COLOR

		annotation SummarizationSetBy = Automatic

	column MARCA
		dataType: string
		lineageTag: c254f066-9b1c-4e70-8294-9cdcb60b4f45
		summarizeBy: none
		sourceColumn: MARCA

		annotation SummarizationSetBy = Automatic

	column GENERO
		dataType: string
		lineageTag: eefb31ec-5333-413c-9868-cd03cd0a2a66
		summarizeBy: none
		sourceColumn: GENERO

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: 88fa6e75-27ef-4419-b4c3-8f2975c5d58d
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column Articulo_GenericoF = MID('EKPO L1 V2'[ARTICULO],FIND("0000000",'EKPO L1 V2'[ARTICULO])+7,8)
		lineageTag: a54f79f3-c17a-400c-a4a1-1a8ef1575219
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Fecha_Conciliacion = ```
			
			IF(
			    'EKPO L1 V2'[ESTADO ENTREGA] = "Entregado", 
			    'EKPO L1 V2'[ULTIMA ENTREGA],
			    EOMONTH('EKPO L1 V2'[F. DESPACHO], 0) + 1
			)
			```
		formatString: Short Date
		lineageTag: 27447876-13d2-4618-8296-a30dde9008f5
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRECIOVENTA_USD =
			
			VAR PrecioUnitario =
			    CALCULATE(
			        FIRSTNONBLANK('Precio Venta'[PrecioVentaUSD], 1),
			        FILTER(
			            ALL('Precio Venta'),
			            'Precio Venta'[Articulo_GenericoF] = 'EKPO L1 V2'[Articulo_GenericoF]
			                && 'Precio Venta'[VKORG] = 'EKPO L1 V2'[SK_PAIS]
			        )
			    )
			VAR Cantidad =
			    IF(
			        'EKPO L1 V2'[ESTADO ENTREGA] = "ENTREGADO",
			        'EKPO L1 V2'[QTY SOLICITADA],
			        'EKPO L1 V2'[PENDIENTE ENTREGA]
			    )
			RETURN
			    PrecioUnitario * Cantidad
			//LOOKUPVALUE(FACT_ARRIBOSFUTURO[PRECIO_VENTANETA_USD],FACT_ARRIBOSFUTURO[DOC],FACT_TUNGYA[DOC_COMPRA],FACT_ARRIBOSFUTURO[ARTICULO],FACT_TUNGYA[ARTICULO]))))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ed550b83-bc31-4848-ba68-74dfba8fcd0b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column FirstDateSale = RELATED(FACT_PRIMERAVENTA_ARTICULO[date_firstsale])
		lineageTag: f6fe93fb-bc9a-43ee-a4ed-34baa07e146c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Estado_Articulo = ```
			
			VAR _Articulo = 'EKPO L1 V2'[Articulo_GenericoF]
			
			-- Fechas de creación para el mismo artículo genérico
			VAR _MinFecha = 
			    CALCULATE(
			        MIN('EKPO L1 V2'[F. CREACION REGISTRO]),
			        ALLEXCEPT('EKPO L1 V2', 'EKPO L1 V2'[Articulo_GenericoF])
			    )
			
			VAR _MaxFecha = 
			    CALCULATE(
			        MAX('EKPO L1 V2'[F. CREACION REGISTRO]),
			        ALLEXCEPT('EKPO L1 V2', 'EKPO L1 V2'[Articulo_GenericoF])
			    )
			
			-- Diferencia en meses entre fechas
			VAR _MesesDiff = DATEDIFF(_MinFecha, _MaxFecha, MONTH)
			
			-- Lógica final
			RETURN
			    IF(
			        _MesesDiff > 1,
			        "Recompra",
			        IF(
			            ISBLANK('EKPO L1 V2'[FirstDateSale]),
			            "Nuevo",
			            IF(
			                'EKPO L1 V2'[FirstDateSale] <= 'EKPO L1 V2'[F. CREACION REGISTRO],
			                "Recompra",
			                "Nuevo"
			            )
			        )
			    )
			```
		lineageTag: 540e89bc-c627-48f2-8ec8-efde37939b3e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SK_PAIS
		dataType: string
		lineageTag: 3033f3f3-3704-4da6-a335-d18bcc5f8c95
		summarizeBy: none
		sourceColumn: SK_PAIS

		annotation SummarizationSetBy = Automatic

	column BV_PAIS
		dataType: string
		lineageTag: 24b2daba-b552-48bf-b7fb-f337bde26590
		summarizeBy: none
		sourceColumn: BV_PAIS

		annotation SummarizationSetBy = Automatic

	column TIPOESTILO
		dataType: string
		lineageTag: 8654b367-cf2c-4147-8705-31b6d1c344a6
		summarizeBy: none
		sourceColumn: TIPOESTILO

		annotation SummarizationSetBy = Automatic

	column BV_CATEGORIA
		dataType: string
		lineageTag: 5b7e7695-706a-4e03-aaf1-445e5c267f25
		summarizeBy: none
		sourceColumn: BV_CATEGORIA

		annotation SummarizationSetBy = Automatic

	column Campaña = LOOKUPVALUE(FAC_TEMPORADAS[Campaña],FAC_TEMPORADAS[Articulo],'EKPO L1 V2'[Articulo_GenericoF],"Sin Campaña")
		lineageTag: 24880504-ceed-4069-9340-a9aaf3079355
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'CLASE DOCUMENTO'
		dataType: string
		lineageTag: d22fdd5c-2722-4121-b6e3-41bd8b4e67f7
		summarizeBy: none
		sourceColumn: CLASE DOCUMENTO

		annotation SummarizationSetBy = Automatic

	column 'F. CREACION REGISTRO'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 174191ac-ba28-4f93-8c62-5e57659fd397
		summarizeBy: none
		sourceColumn: F. CREACION REGISTRO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'GRUPO DE COMPRAS'
		dataType: string
		lineageTag: 3aa15c27-f56b-4605-b067-89aad8adfd1e
		summarizeBy: none
		sourceColumn: GRUPO DE COMPRAS

		annotation SummarizationSetBy = Automatic

	column 'CENTRO SUMINISTRADOR'
		dataType: string
		lineageTag: 0cb7b8d6-32ae-4688-a62e-924ea66c2207
		summarizeBy: none
		sourceColumn: CENTRO SUMINISTRADOR

		annotation SummarizationSetBy = Automatic

	column 'F. DESPACHO'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 63621137-9570-4348-8de3-0f1a8db269f5
		summarizeBy: none
		sourceColumn: F. DESPACHO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CENTRO DESTINO'
		dataType: string
		lineageTag: b59e3dd9-d5d8-45e7-afb5-b3bedce48905
		summarizeBy: none
		sourceColumn: CENTRO DESTINO

		annotation SummarizationSetBy = Automatic

	column 'DOC. POS'
		dataType: string
		lineageTag: c73ec617-7406-44b7-b5da-7fae615c4a58
		summarizeBy: none
		sourceColumn: DOC. POS

		annotation SummarizationSetBy = Automatic

	column 'CENTRO ENTREGA'
		dataType: string
		lineageTag: fa70b355-344e-4cf9-bb12-ce10fd7a26f4
		summarizeBy: none
		sourceColumn: CENTRO ENTREGA

		annotation SummarizationSetBy = Automatic

	column 'QTY SOLICITADA'
		dataType: double
		lineageTag: 44576676-9aa6-4927-98b8-88dad292a099
		summarizeBy: sum
		sourceColumn: QTY SOLICITADA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNIDAD
		dataType: string
		lineageTag: c10f1399-1ea9-4e0c-b801-980d828c2fba
		summarizeBy: none
		sourceColumn: UNIDAD

		annotation SummarizationSetBy = Automatic

	column 'TIPO MATERIAL'
		dataType: string
		lineageTag: 682fc1e6-de1f-4690-b215-e3a6fa4f7f56
		summarizeBy: none
		sourceColumn: TIPO MATERIAL

		annotation SummarizationSetBy = Automatic

	column 'PE AÑO'
		dataType: string
		lineageTag: 3d36c3af-e7ff-4405-a7db-7fff87b8efc1
		summarizeBy: none
		sourceColumn: PE AÑO

		annotation SummarizationSetBy = Automatic

	column 'QTY ENTREGADA'
		dataType: double
		lineageTag: 02dacdd4-2f3f-464e-a8a0-525fa8975b04
		summarizeBy: sum
		sourceColumn: QTY ENTREGADA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PENDIENTE ENTREGA'
		dataType: double
		lineageTag: 62dd113f-903f-41ac-abb0-d6fabcb30e76
		summarizeBy: sum
		sourceColumn: PENDIENTE ENTREGA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ULTIMA ENTREGA'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5a5abdf6-cb87-4de7-b214-353ea1f369aa
		summarizeBy: none
		sourceColumn: ULTIMA ENTREGA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ESTADO ENTREGA'
		dataType: string
		lineageTag: c430c8d1-735a-48ff-81c1-79d5f7b23d2b
		summarizeBy: none
		sourceColumn: ESTADO ENTREGA

		annotation SummarizationSetBy = Automatic

	partition 'EKPO L1 V2' = m
		mode: import
		source =
				let
				    Consulta1 = Value.NativeQuery(SapHana.Database("vhadoahpdb01.hec.empresasadoc.com:30215", [Implementation="2.0"]), "--SQL PARA L1--#(lf)SELECT#(lf)    EKKO.EBELN AS ""DOCUMENTO"",#(lf)    EKKO.BSART AS ""CLASE DOCUMENTO"",#(lf)    EKKO.AEDAT AS ""F. CREACION REGISTRO"",#(lf)    EKKO.EKGRP AS ""GRUPO DE COMPRAS"",#(lf)    EKKO.RESWK AS ""CENTRO SUMINISTRADOR"",#(lf)    EKKO.ZZF_DESPACHO AS ""F. DESPACHO"",#(lf)    EKKO.ZZ_CENTRO_D AS ""CENTRO DESTINO"",#(lf)    #(lf)    EKPO.EBELP AS ""DOC. POS"",#(lf)    EKPO.TXZ01 AS ""DESCRIPCION"",#(lf)    EKPO.MATNR AS ""ARTICULO"",#(lf)    EKPO.WERKS AS ""CENTRO ENTREGA"",#(lf)    EKPO.LGORT AS ""ALMACEN"",#(lf)    EKPO.MENGE AS ""QTY SOLICITADA"",#(lf)    EKPO.MEINS AS ""UNIDAD"",#(lf)    EKPO.MTART AS ""TIPO MATERIAL"",#(lf)    #(lf)    MARA.GROES AS ""ESTILO"",#(lf)    MARA.FREE_CHAR AS ""COLOR"",#(lf)    MARA.BRAND_ID AS ""MARCA"",#(lf)    MARA.ZZ_ART_PROV AS ""GENERO"",#(lf)    MARA.ZZ_DEPART AS ""DEPARTAMENTO"",#(lf)    MARA.SAISO AS ""PE"",#(lf)    MARA.SAISJ AS ""PE AÑO"",#(lf)    #(lf)    COALESCE(MSEG_SUM.QTY_ENTREGADA, 0) AS ""QTY ENTREGADA"",#(lf)    (EKPO.MENGE - COALESCE(MSEG_SUM.QTY_ENTREGADA, 0)) AS ""PENDIENTE ENTREGA"",#(lf)    MSEG_SUM.ULTIMA_FECHA AS ""ULTIMA ENTREGA"",#(lf)    CASE#(lf)        WHEN COALESCE(MSEG_SUM.QTY_ENTREGADA, 0) >= EKPO.MENGE THEN 'ENTREGADO'#(lf)        WHEN COALESCE(MSEG_SUM.QTY_ENTREGADA, 0) > 0 THEN 'PARCIAL'#(lf)        ELSE 'PENDIENTE'#(lf)    END AS ""ESTADO ENTREGA""#(lf)FROM SAP_ECC.EKPO#(lf)LEFT JOIN SAP_ECC.EKKO #(lf)    ON EKPO.EBELN = EKKO.EBELN#(lf)LEFT JOIN SAP_ECC.MARA #(lf)    ON EKPO.MATNR = MARA.MATNR#(lf)LEFT JOIN (#(lf)    SELECT EBELN, EBELP, #(lf)           SUM(MENGE) AS QTY_ENTREGADA,#(lf)           MAX(BUDAT_MKPF) AS ULTIMA_FECHA#(lf)    FROM SAP_ECC.MSEG#(lf)    WHERE BWART = '101'#(lf)    GROUP BY EBELN, EBELP#(lf)) MSEG_SUM#(lf)    ON EKPO.EBELN = MSEG_SUM.EBELN#(lf)    AND EKPO.EBELP = MSEG_SUM.EBELP#(lf)WHERE#(lf)    --EKKO.EKGRP = '303'#(lf)    EKKO.RESWK IN ('1000', '1020')#(lf)    AND EKPO.LOEKZ <> 'L'#(lf)    AND EKKO.AEDAT >= ADD_MONTHS(CURRENT_DATE, -24)#(lf)    --AND EKKO.EBELN = '4801958149'#(lf)    --AND EKPO.MATNR LIKE '%10013858001%'", null, [EnableFolding=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Consulta1,{{"F. CREACION REGISTRO", type date}, {"F. DESPACHO", type date},{"ULTIMA ENTREGA", type date}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado", {"CENTRO DESTINO"}, DIM_BODEGA, {"SK_TIENDA"}, "DIM_BODEGA", JoinKind.LeftOuter),
				    #"Se expandió DIM_BODEGA" = Table.ExpandTableColumn(#"Consultas combinadas", "DIM_BODEGA", {"SK_PAIS"}, {"SK_PAIS"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Se expandió DIM_BODEGA", {"SK_PAIS"}, DIM_PAIS, {"SK_PAIS"}, "DIM_PAIS", JoinKind.LeftOuter),
				    #"Se expandió DIM_PAIS" = Table.ExpandTableColumn(#"Consultas combinadas1", "DIM_PAIS", {"BV_PAIS"}, {"BV_PAIS"}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Se expandió DIM_PAIS", {"ARTICULO"}, DIM_ARTICULOS, {"SK_MATNR"}, "DIM_ARTICULOS", JoinKind.LeftOuter),
				    #"Se expandió DIM_ARTICULOS" = Table.ExpandTableColumn(#"Consultas combinadas2", "DIM_ARTICULOS", {"TIPOESTILO"}, {"TIPOESTILO"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Se expandió DIM_ARTICULOS", {"ARTICULO"}, DIM_ARTICULOS, {"SK_MATNR"}, "DIM_ARTICULOS", JoinKind.LeftOuter),
				    #"Se expandió DIM_ARTICULOS1" = Table.ExpandTableColumn(#"Consultas combinadas3", "DIM_ARTICULOS", {"BV_CATEGORIA"}, {"BV_CATEGORIA"})
				in
				    #"Se expandió DIM_ARTICULOS1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

