table FACT_PRIMERAVENTA_ARTICULO
	lineageTag: 3f4bd7a9-aa32-4aa3-ad1a-3f9eac6bb92e

	column date_firstsale
		dataType: dateTime
		formatString: General Date
		lineageTag: 6abec471-4646-4c46-bb5f-a3645abc4551
		summarizeBy: none
		sourceColumn: date_firstsale

		annotation SummarizationSetBy = Automatic

	column SK_ARTICULO
		dataType: string
		lineageTag: ddbbf10a-6a91-49b5-908d-1c0e8fac8ef2
		summarizeBy: none
		sourceColumn: SK_ARTICULO

		annotation SummarizationSetBy = Automatic

	partition FACT_PRIMERAVENTA_ARTICULO = m
		mode: import
		source =
				let
				    Origen = Sql.Database("192.168.16.74", "DM_COMERCIAL", [Query="select * from DM_BI.dbo.FACT_PRIMERAVENTA_ARTICULO"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"date_firstsale", type text}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Tipo cambiado",{{"date_firstsale", type date}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Tipo cambiado1",{{"date_firstsale", type datetime}})
				in
				    #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

