table 'SLA CDs'
	lineageTag: 5b0db0ca-6dc3-48b0-a681-e82bf136f230

	column Descripción
		dataType: string
		lineageTag: c6bdd83f-e128-408f-89de-b031f6b2d3cb
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column BV_PAIS
		dataType: string
		lineageTag: 863abba6-2f28-46a4-aa06-1229cbdb4c77
		summarizeBy: none
		sourceColumn: BV_PAIS

		annotation SummarizationSetBy = Automatic

	column LT
		dataType: string
		lineageTag: 84c5b167-5dbe-401d-98da-7ef67b4052f1
		summarizeBy: none
		sourceColumn: LT

		annotation SummarizationSetBy = Automatic

	partition 'SLA CDs' = m
		mode: import
		queryGroup: 'Base LeadTimes'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents("https://empresasadoc-my.sharepoint.com/personal/no-reply_empresasadoc_com/Documents/TEMP_Sharepoint/Lead%20Time%20para%20Modelo%20Panama.xlsx"), null, true),
				    #"SLA CDs_Sheet" = Origen{[Item="SLA CDs",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"SLA CDs_Sheet", [PromoteAllScalars=true]),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Encabezados promovidos", {"Descripción"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna de anulación de dinamización",{{"Atributo", "BV_PAIS"}, {"Valor", "LT"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

