table 'Tiempos Export'
	lineageTag: d3164c40-6b5a-4ecb-a841-8b1931219da0

	column Tipo
		dataType: string
		lineageTag: d8316465-f907-40c6-b89e-69cd4ce37293
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: ce3b45cf-8a4d-471b-84a8-634c685594ce
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column BV_PAIS
		dataType: string
		lineageTag: caa6af26-d586-45f8-a29d-9760f119b5b1
		summarizeBy: none
		sourceColumn: BV_PAIS

		annotation SummarizationSetBy = Automatic

	column LT
		dataType: string
		lineageTag: 738d0da9-9274-4cf6-8447-1eba2b72b685
		summarizeBy: none
		sourceColumn: LT

		annotation SummarizationSetBy = Automatic

	partition 'Tiempos Export' = m
		mode: import
		queryGroup: 'Base LeadTimes'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents("https://empresasadoc-my.sharepoint.com/personal/no-reply_empresasadoc_com/Documents/TEMP_Sharepoint/Lead%20Time%20para%20Modelo%20Panama.xlsx"), null, true),
				    #"Tiempos Export_Sheet" = Origen{[Item="Tiempos Export",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tiempos Export_Sheet", [PromoteAllScalars=true]),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Encabezados promovidos", {"Tipo", "Descripción"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna de anulación de dinamización",{{"Atributo", "BV_PAIS"}, {"Valor", "LT"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

