table 'Tiempos Inbound'
	lineageTag: 89e03991-7d77-448c-810e-e277fea45945

	column Modalidad
		dataType: string
		lineageTag: 6f92fb68-d89b-4541-9b7f-911277c4bd9c
		summarizeBy: none
		sourceColumn: Modalidad

		annotation SummarizationSetBy = Automatic

	column Origen
		dataType: string
		lineageTag: 9df1b518-e4d4-4832-995e-dad1cc99cd82
		summarizeBy: none
		sourceColumn: Origen

		annotation SummarizationSetBy = Automatic

	column Actividad
		dataType: string
		lineageTag: d9006447-4308-4c39-997b-ed9a452df936
		summarizeBy: none
		sourceColumn: Actividad

		annotation SummarizationSetBy = Automatic

	column LT
		dataType: string
		lineageTag: 48d3773f-e5bc-46fb-940c-b3632c211c08
		summarizeBy: none
		sourceColumn: LT

		annotation SummarizationSetBy = Automatic

	partition 'Tiempos Inbound' = m
		mode: import
		queryGroup: 'Base LeadTimes'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents("https://empresasadoc-my.sharepoint.com/personal/no-reply_empresasadoc_com/Documents/TEMP_Sharepoint/Lead%20Time%20para%20Modelo%20Panama.xlsx"), null, true),
				    #"Tiempos Inbound_Sheet" = Origen{[Item="Tiempos Inbound",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tiempos Inbound_Sheet", [PromoteAllScalars=true]),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Encabezados promovidos", {"Modalidad", "Origen"}, "Atributo", "Valor"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna de anulación de dinamización",{{"Atributo", "Actividad"}, {"Valor", "LT"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

