table 'INV ACTUAL'
	lineageTag: 2eb77427-871d-4d84-8650-f53775c99941

	column KEY = 'INV ACTUAL'[MARCA BV2]&'INV ACTUAL'[PAIS BV]&'INV ACTUAL'[DEPTO BV]&'INV ACTUAL'[GENERO BV]&'INV ACTUAL'[CATEGORIA BV]
		lineageTag: 00c42fea-2770-4f55-89e2-9f9784a822a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'VALOR $ PROMEDIO' = IFERROR('INV ACTUAL'[EXISTENCIA NETA $ ULTIMO DIA]/'INV ACTUAL'[EXISTENCIA PARES ULTIMO DIA],'INV ACTUAL'[EXISTENCIA NETA $ ULTIMO DIA])
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: 68917ee7-1ea9-4d18-b13d-a1965be2fa38
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-SV"}

	column 'EXISTENCIA DISPONIBLE $' = 'INV ACTUAL'[PARES DISPONIBLE ULTIMO DIA]*'INV ACTUAL'[VALOR $ PROMEDIO]
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: df38e7d8-bf8f-4e46-9150-b056ac41b92a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-SV"}

	column 'MARCA BV2' = TRIM(IF(LOOKUPVALUE('MARCAS UNIDAD'[UNIDAD NEGOCIO],'MARCAS UNIDAD'[MARCA BV],'INV ACTUAL'[MARCA BV])="PAR2","PAR2",'INV ACTUAL'[MARCA BV]))
		lineageTag: 095be5d3-8177-4305-ac78-5018796e79c3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PE
		dataType: string
		lineageTag: af1ad00f-7bcb-4e88-81cc-94eccd78aaaa
		summarizeBy: none
		sourceColumn: PE

		annotation SummarizationSetBy = Automatic

	column MES_LANZ = RELATED('TABLA PE'[AÑO MES LANZAMIENTO])
		lineageTag: 712b9c00-e9e8-4e75-a6be-add5d3a61ea3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'PAIS BV'
		dataType: string
		lineageTag: 9f137753-6c88-40a4-a2da-b4a77de0779f
		summarizeBy: none
		sourceColumn: PAIS BV

		annotation SummarizationSetBy = Automatic

	column 'COD ALMACEN'
		dataType: string
		lineageTag: 5d33ca1d-1036-4c10-b32b-f2e0ad73888f
		summarizeBy: none
		sourceColumn: COD ALMACEN

		annotation SummarizationSetBy = Automatic

	column 'MARCA BV'
		dataType: string
		lineageTag: 9d81441d-013e-4611-a8d5-16ff756f0f07
		summarizeBy: none
		sourceColumn: MARCA BV

		annotation SummarizationSetBy = Automatic

	column 'DEPTO BV'
		dataType: string
		lineageTag: d0fd2f95-535e-4af7-9806-7364a4fc6f5b
		summarizeBy: none
		sourceColumn: DEPTO BV

		annotation SummarizationSetBy = Automatic

	column 'GENERO BV'
		dataType: string
		lineageTag: 951c3f4b-ad14-4069-ade0-af9a7ea14e3c
		summarizeBy: none
		sourceColumn: GENERO BV

		annotation SummarizationSetBy = Automatic

	column 'CATEGORIA BV'
		dataType: string
		lineageTag: 824aa939-029b-4f99-93ec-f75c780dcc66
		summarizeBy: none
		sourceColumn: CATEGORIA BV

		annotation SummarizationSetBy = Automatic

	column 'TIPO ESTILO'
		dataType: string
		lineageTag: c98fd98a-74de-46f0-8f9a-e4b9862782ab
		summarizeBy: none
		sourceColumn: TIPO ESTILO

		annotation SummarizationSetBy = Automatic

	column 'EXISTENCIA PARES ULTIMO DIA'
		dataType: int64
		formatString: 0
		lineageTag: 0ef2bbec-0e1f-412b-acbf-08da1007bef5
		summarizeBy: sum
		sourceColumn: EXISTENCIA PARES ULTIMO DIA

		annotation SummarizationSetBy = Automatic

	column 'EXISTENCIA NETA $ ULTIMO DIA'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 2d500258-714a-4b9b-aa0d-025972749142
		summarizeBy: sum
		sourceColumn: EXISTENCIA NETA $ ULTIMO DIA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-SV"}

	column 'PARES DISPONIBLE ULTIMO DIA'
		dataType: int64
		formatString: 0
		lineageTag: 7136fea0-e8e4-4f72-a97a-554d226fdc4e
		summarizeBy: sum
		sourceColumn: PARES DISPONIBLE ULTIMO DIA

		annotation SummarizationSetBy = Automatic

	partition 'INV ACTUAL' = m
		mode: import
		queryGroup: 'Server Cognos (74)'
		source =
				let
				    Source = Sql.Database("192.168.16.74", "DM_COMERCIAL", [Query="#(lf)select#(lf)#(tab)(coalesce(""D"".""PAIS_BV"", ""D3"".""PAIS_BV"")) ""PAIS_BV"" ,#(lf)#(tab)(coalesce(""D"".""COD_ALMACEN"", ""D3"".""COD_ALMACEN"")) ""COD_ALMACEN"" ,#(lf)#(tab)(coalesce(""D"".""MARCA_BV"", ""D3"".""MARCA_BV"")) ""MARCA_BV"" ,#(lf)#(tab)(coalesce(""D"".""DEPTO_BV"", ""D3"".""DEPTO_BV"")) ""DEPTO_BV"" ,#(lf)#(tab)(coalesce(""D"".""GENERO_BV"", ""D3"".""GENERO_BV"")) ""GENERO_BV"" ,#(lf)#(tab)(coalesce(""D"".""CATEGORIA_BV"", ""D3"".""CATEGORIA_BV"")) ""CATEGORIA_BV"" ,#(lf)#(tab)""D3"".""EXISTENCIA_PARES_ULTIMO_DIA"" ""EXISTENCIA_PARES_ULTIMO_DIA"" ,#(lf)#(tab)""D3"".""EXISTENCIA_NETA___ULTIMO_DIA"" ""EXISTENCIA_NETA___ULTIMO_DIA"" ,#(lf)#(tab)""D3"".""PARES_DISPONIBLE_ULTIMO_DIA"" ""PARES_DISPONIBLE_ULTIMO_DIA"" ,#(lf)#(tab)(coalesce(""D"".""TIPO_ESTILO"", ""D3"".""TIPO_ESTILO"")) ""TIPO_ESTILO"" ,#(lf)#(tab)(coalesce(""D"".""COD_TIPO_OPERACION"", ""D3"".""COD_TIPO_OPERACION"")) ""COD_TIPO_OPERACION"" ,#(lf)#(tab)(coalesce(""D"".""TIPO_OPERACION"", ""D3"".""TIPO_OPERACION"")) ""TIPO_OPERACION"" ,#(lf)#(tab)""D"".""ARRIBO_PARES_ULTIMO_DIA"" ""ARRIBO_PARES_ULTIMO_DIA"" ,#(lf)#(tab)""D"".""ARRIBO_NETO___ULTIMO_DIA"" ""ARRIBO_NETO___ULTIMO_DIA"" ,#(lf)#(tab)(coalesce(""D"".""COD_TEMPORADA_SAP"", ""D3"".""COD_TEMPORADA_SAP"")) ""COD_TEMPORADA_SAP""#(lf)from#(lf)#(tab)(#(lf)#(tab)select#(lf)#(tab)#(tab)""DIM_PAIS"".""BV_PAIS"" ""PAIS_BV"" ,#(lf)#(tab)#(tab)""DIM_ALMACEN"".""SK_ALMACEN"" ""COD_ALMACEN"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_MARCA"" ""MARCA_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_DEPTO"" ""DEPTO_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_GENERO"" ""GENERO_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_CATEGORIA"" ""CATEGORIA_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""TIPOESTILO"" ""TIPO_ESTILO"" ,#(lf)#(tab)#(tab)""DIM_TIPOOPERACION"".""SK_TIPOOPERACION"" ""COD_TIPO_OPERACION"" ,#(lf)#(tab)#(tab)""DIM_TIPOOPERACION"".""TIPO_OPERACION"" ""TIPO_OPERACION"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""SK_COLECCION"" ""COD_TEMPORADA_SAP"" ,#(lf)#(tab)#(tab)sum(""FAC_ARRIBOFUTUROUD4"".""PARES"") ""ARRIBO_PARES_ULTIMO_DIA"" ,#(lf)#(tab)#(tab)sum(""FAC_ARRIBOFUTUROUD4"".""PRECIO_VENTANETA_USD"") ""ARRIBO_NETO___ULTIMO_DIA""#(lf)#(tab)from#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_PAIS"" ""DIM_PAIS"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_ALMACEN"" ""DIM_ALMACEN"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_ARTICULOSAP"" ""DIM_ARTICULOSAP"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_TIPOOPERACION"" ""DIM_TIPOOPERACION"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""FAC_ARRIBOFUTUROUD"" ""FAC_ARRIBOFUTUROUD4"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_TIENDA"" ""DIM_TIENDA""#(lf)#(tab)where#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""SK_CATEGORIA"" NOT in (N'PR', N'G4')#(lf)#(tab)#(tab)and ""DIM_ARTICULOSAP"".""SK_DEPTO"" in (N'A', N'C', N'R')#(lf)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" NOT in ('0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019', '0020')#(lf)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" NOT in ('0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019', '0020')#(lf)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" NOT in ('0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019', '0020')#(lf)#(tab)#(tab)and ""DIM_PAIS"".""SK_PAIS"" = ""FAC_ARRIBOFUTUROUD4"".""SK_PAIS""#(lf)#(tab)#(tab)and ""FAC_ARRIBOFUTUROUD4"".""SK_ALMACEN"" = ""DIM_ALMACEN"".""SK_ALMACEN""#(lf)#(tab)#(tab)and ""FAC_ARRIBOFUTUROUD4"".""SK_MATNR"" = ""DIM_ARTICULOSAP"".""SK_MATNR""#(lf)#(tab)#(tab)and ""FAC_ARRIBOFUTUROUD4"".""SK_TIENDA"" = ""DIM_TIENDA"".""SK_TIENDA""#(lf)#(tab)#(tab)and ""FAC_ARRIBOFUTUROUD4"".""SK_TIPOOPERACION"" = ""DIM_TIPOOPERACION"".""SK_TIPOOPERACION""#(lf)#(tab)group by#(lf)#(tab)#(tab)""DIM_PAIS"".""BV_PAIS"",#(lf)#(tab)#(tab)""DIM_ALMACEN"".""SK_ALMACEN"",#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_MARCA"",#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_DEPTO"",#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_GENERO"",#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_CATEGORIA"",#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""TIPOESTILO"",#(lf)#(tab)#(tab)""DIM_TIPOOPERACION"".""SK_TIPOOPERACION"",#(lf)#(tab)#(tab)""DIM_TIPOOPERACION"".""TIPO_OPERACION"",#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""SK_COLECCION"") ""D""#(lf)FULL OUTER JOIN (#(lf)#(tab)select#(lf)#(tab)#(tab)""DIM_PAIS"".""BV_PAIS"" ""PAIS_BV"" ,#(lf)#(tab)#(tab)""DIM_ALMACEN"".""SK_ALMACEN"" ""COD_ALMACEN"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_MARCA"" ""MARCA_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_DEPTO"" ""DEPTO_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_GENERO"" ""GENERO_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_CATEGORIA"" ""CATEGORIA_BV"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""TIPOESTILO"" ""TIPO_ESTILO"" ,#(lf)#(tab)#(tab)""DIM_TIPOOPERACION"".""SK_TIPOOPERACION"" ""COD_TIPO_OPERACION"" ,#(lf)#(tab)#(tab)""DIM_TIPOOPERACION"".""TIPO_OPERACION"" ""TIPO_OPERACION"" ,#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""SK_COLECCION"" ""COD_TEMPORADA_SAP"" ,#(lf)#(tab)#(tab)sum(""FAC_INVENTARIOUD5"".""PARES"") ""EXISTENCIA_PARES_ULTIMO_DIA"" ,#(lf)#(tab)#(tab)sum(""FAC_INVENTARIOUD5"".""PRECIO_USD"") ""EXISTENCIA_NETA___ULTIMO_DIA"" ,#(lf)#(tab)#(tab)sum(""FAC_INVENTARIOUD5"".""DISPONIBLE"") ""PARES_DISPONIBLE_ULTIMO_DIA""#(lf)#(tab)from#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_PAIS"" ""DIM_PAIS"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_ALMACEN"" ""DIM_ALMACEN"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_ARTICULOSAP"" ""DIM_ARTICULOSAP"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_TIPOOPERACION"" ""DIM_TIPOOPERACION"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""FAC_INVENTARIOUD"" ""FAC_INVENTARIOUD5"",#(lf)#(tab)#(tab)""DM_COMERCIAL"".""dbo"".""DIM_TIENDA"" ""DIM_TIENDA""#(lf)#(tab)where#(lf)#(tab)#(tab)""DIM_ARTICULOSAP"".""SK_CATEGORIA"" NOT in (N'PR', N'G4')#(lf)#(tab)#(tab)#(tab)and ""DIM_ARTICULOSAP"".""SK_DEPTO"" in (N'A', N'C', N'R')#(lf)#(tab)#(tab)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" NOT in ('0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019', '0020')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" NOT in ('0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019', '0020')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" NOT in ('0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011', '0012', '0013', '0014', '0015', '0016', '0017', '0018', '0019', '0020')#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)and ""FAC_INVENTARIOUD5"".""SK_PAIS"" = ""DIM_PAIS"".""SK_PAIS""#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)and ""DIM_ALMACEN"".""SK_ALMACEN"" = ""FAC_INVENTARIOUD5"".""SK_ALMACEN""#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)and ""DIM_ARTICULOSAP"".""SK_MATNR"" = ""FAC_INVENTARIOUD5"".""SK_MATNR""#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)and ""DIM_TIENDA"".""SK_TIENDA"" = ""FAC_INVENTARIOUD5"".""SK_TIENDA""#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)and ""FAC_INVENTARIOUD5"".""SK_TIPOOPERACION"" = ""DIM_TIPOOPERACION"".""SK_TIPOOPERACION""#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)group by#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_PAIS"".""BV_PAIS"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ALMACEN"".""SK_ALMACEN"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_MARCA"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_DEPTO"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_GENERO"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ARTICULOSAP"".""BV_CATEGORIA"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ARTICULOSAP"".""TIPOESTILO"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_TIPOOPERACION"".""SK_TIPOOPERACION"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_TIPOOPERACION"".""TIPO_OPERACION"",#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)""DIM_ARTICULOSAP"".""SK_COLECCION"") ""D3"" on#(lf)#(tab)""D"".""PAIS_BV"" = ""D3"".""PAIS_BV""#(lf)#(tab)and ""D"".""COD_ALMACEN"" = ""D3"".""COD_ALMACEN""#(lf)#(tab)and ""D"".""MARCA_BV"" = ""D3"".""MARCA_BV""#(lf)#(tab)and ""D"".""DEPTO_BV"" = ""D3"".""DEPTO_BV""#(lf)#(tab)and ""D"".""GENERO_BV"" = ""D3"".""GENERO_BV""#(lf)#(tab)and ""D"".""CATEGORIA_BV"" = ""D3"".""CATEGORIA_BV""#(lf)#(tab)and ""D"".""TIPO_ESTILO"" = ""D3"".""TIPO_ESTILO""#(lf)#(tab)and ""D"".""COD_TIPO_OPERACION"" = ""D3"".""COD_TIPO_OPERACION""#(lf)#(tab)and ""D"".""TIPO_OPERACION"" = ""D3"".""TIPO_OPERACION""#(lf)#(tab)and ""D"".""COD_TEMPORADA_SAP"" = ""D3"".""COD_TEMPORADA_SAP""", CreateNavigationProperties=false]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"PAIS_BV", "PAIS BV"}, {"COD_ALMACEN", "COD ALMACEN"}, {"MARCA_BV", "MARCA BV"}, {"DEPTO_BV", "DEPTO BV"}, {"GENERO_BV", "GENERO BV"}, {"CATEGORIA_BV", "CATEGORIA BV"}, {"EXISTENCIA_PARES_ULTIMO_DIA", "EXISTENCIA PARES ULTIMO DIA"}, {"EXISTENCIA_NETA___ULTIMO_DIA", "EXISTENCIA NETA $ ULTIMO DIA"}, {"PARES_DISPONIBLE_ULTIMO_DIA", "PARES DISPONIBLE ULTIMO DIA"}, {"TIPO_ESTILO", "TIPO ESTILO"}, {"COD_TIPO_OPERACION", "COD TIPO OPERACION"}, {"TIPO_OPERACION", "TIPO OPERACION"}, {"ARRIBO_PARES_ULTIMO_DIA", "ARRIBO PARES ULTIMO DIA"}, {"ARRIBO_NETO___ULTIMO_DIA", "ARRIBO NETO ULTIMO DIA"}, {"COD_TEMPORADA_SAP", "COD TEMPORADA SAP"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"PAIS BV", "COD ALMACEN", "MARCA BV", "DEPTO BV", "GENERO BV", "CATEGORIA BV", "TIPO ESTILO", "EXISTENCIA PARES ULTIMO DIA", "EXISTENCIA NETA $ ULTIMO DIA", "PARES DISPONIBLE ULTIMO DIA", "COD TEMPORADA SAP"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"PARES DISPONIBLE ULTIMO DIA", Int64.Type}, {"EXISTENCIA NETA $ ULTIMO DIA", Currency.Type}, {"EXISTENCIA PARES ULTIMO DIA", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([TIPO ESTILO] <> "NOS")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [EXISTENCIA PARES ULTIMO DIA] > 0),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [#"EXISTENCIA NETA $ ULTIMO DIA"] > 0),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows2", {"PAIS BV", "COD ALMACEN", "MARCA BV", "DEPTO BV", "GENERO BV", "CATEGORIA BV", "TIPO ESTILO", "COD TEMPORADA SAP"}, {{"EXISTENCIA PARES ULTIMO DIA", each List.Sum([EXISTENCIA PARES ULTIMO DIA]), type nullable number}, {"EXISTENCIA NETA $ ULTIMO DIA", each List.Sum([#"EXISTENCIA NETA $ ULTIMO DIA"]), type nullable number}, {"PARES DISPONIBLE ULTIMO DIA", each List.Sum([PARES DISPONIBLE ULTIMO DIA]), type nullable number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Grouped Rows",{{"EXISTENCIA PARES ULTIMO DIA", Int64.Type}, {"EXISTENCIA NETA $ ULTIMO DIA", Currency.Type}, {"PARES DISPONIBLE ULTIMO DIA", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "PE", each Text.Start([COD TEMPORADA SAP],4)),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom",{"PAIS BV", "COD ALMACEN", "MARCA BV", "DEPTO BV", "GENERO BV", "CATEGORIA BV", "TIPO ESTILO", "EXISTENCIA PARES ULTIMO DIA", "EXISTENCIA NETA $ ULTIMO DIA", "PARES DISPONIBLE ULTIMO DIA", "PE"})
				in
				    #"Removed Other Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

