table 'TRANS TDAS'
	lineageTag: 7fa4e3a7-8bd9-494a-9b2c-482224726d61

	column 'Doc.compr.'
		dataType: int64
		formatString: 0
		lineageTag: c63e2927-1b3b-4276-8d67-ea9388816dc9
		summarizeBy: sum
		sourceColumn: Doc.compr.

		annotation SummarizationSetBy = Automatic

	column Artículo
		dataType: int64
		formatString: 0
		lineageTag: b4971b98-1b77-459c-9b19-28bcb8374f23
		summarizeBy: none
		sourceColumn: Artículo

		annotation SummarizationSetBy = Automatic

	column UMP
		dataType: string
		lineageTag: c6b7e767-68aa-4136-84f9-f741f9a53f75
		summarizeBy: none
		sourceColumn: UMP

		annotation SummarizationSetBy = Automatic

	column 'Cl.'
		dataType: string
		lineageTag: a4c6117d-abfb-408d-b97a-39f5b3849ae0
		summarizeBy: none
		sourceColumn: Cl.

		annotation SummarizationSetBy = Automatic

	column 'Creado el'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ba520ab7-2a65-4802-9ba6-ba2a6126de1f
		summarizeBy: none
		sourceColumn: Creado el

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Creado por'
		dataType: string
		lineageTag: b4e3b98b-c111-4ef3-808d-425cb1c4c5ba
		summarizeBy: none
		sourceColumn: Creado por

		annotation SummarizationSetBy = Automatic

	column CeSu
		dataType: int64
		formatString: 0
		lineageTag: 7b190c9d-73ca-4326-b40d-5cce24face31
		summarizeBy: sum
		sourceColumn: CeSu

		annotation SummarizationSetBy = Automatic

	column 'Texto breve'
		dataType: string
		lineageTag: fb90d603-0462-4eac-ba86-e6c094928077
		summarizeBy: none
		sourceColumn: Texto breve

		annotation SummarizationSetBy = Automatic

	column 'Ce.'
		dataType: int64
		formatString: 0
		lineageTag: fe632453-2d5d-4c56-ad7c-a638dd7c8e7a
		summarizeBy: sum
		sourceColumn: Ce.

		annotation SummarizationSetBy = Automatic

	column TpMt
		dataType: string
		lineageTag: 323e4737-f395-44b5-8c2f-a266b519a9ca
		summarizeBy: none
		sourceColumn: TpMt

		annotation SummarizationSetBy = Automatic

	column 'Denom. Estilo'
		dataType: string
		lineageTag: 56c82058-03fb-47e0-9194-7c3aae1e96b9
		summarizeBy: none
		sourceColumn: Denom. Estilo

		annotation SummarizationSetBy = Automatic

	column 'Mat.gral.conf.'
		dataType: int64
		formatString: 0
		lineageTag: fdf30fe2-d000-4e5b-a6a8-971a2d3e5617
		summarizeBy: sum
		sourceColumn: Mat.gral.conf.

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 17bf3cd0-73be-40fe-b18b-2e479c18fcfb
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Tam.1'
		dataType: string
		lineageTag: 567756a8-3acb-4b12-8910-850f43e72b24
		summarizeBy: none
		sourceColumn: Tam.1

		annotation SummarizationSetBy = Automatic

	column Marca
		dataType: string
		lineageTag: 964f5baf-4dca-4778-94ac-444866acb2d2
		summarizeBy: none
		sourceColumn: Marca

		annotation SummarizationSetBy = Automatic

	column Genero
		dataType: string
		lineageTag: 90e711c6-4d12-4ed6-8abe-b64f069f79b4
		summarizeBy: none
		sourceColumn: Genero

		annotation SummarizationSetBy = Automatic

	column 'Nombre 1'
		dataType: string
		lineageTag: 41310846-231c-4be8-acea-da72f635177e
		summarizeBy: none
		sourceColumn: Nombre 1

		annotation SummarizationSetBy = Automatic

	column Ps
		dataType: string
		lineageTag: 1024bdd8-da99-4a2a-8da8-dc1e84efdd20
		summarizeBy: none
		sourceColumn: Ps

		annotation SummarizationSetBy = Automatic

	column B
		dataType: string
		lineageTag: 2050de23-cbb8-4bc8-a956-1c1f384c9bd3
		summarizeBy: none
		sourceColumn: B

		annotation SummarizationSetBy = Automatic

	column Departamento
		dataType: string
		lineageTag: ee713c91-1bc0-498e-bd54-f4f3f76b163d
		summarizeBy: none
		sourceColumn: Departamento

		annotation SummarizationSetBy = Automatic

	column 'Caráct.01'
		dataType: string
		lineageTag: 3c58255e-c458-47a9-b663-010cc31f67da
		summarizeBy: none
		sourceColumn: Caráct.01

		annotation SummarizationSetBy = Automatic

	column Vendedor/a
		dataType: string
		lineageTag: 9fa5f621-c0be-4e30-9516-8128963395df
		summarizeBy: none
		sourceColumn: Vendedor/a

		annotation SummarizationSetBy = Automatic

	column AlmEmi
		dataType: string
		lineageTag: 75d70961-9b4e-4954-922e-38fb8f3f1eb7
		summarizeBy: none
		sourceColumn: AlmEmi

		annotation SummarizationSetBy = Automatic

	column 'Alm.'
		dataType: string
		lineageTag: 05a64bfa-fe73-460e-84ba-d2244afb42ff
		summarizeBy: none
		sourceColumn: Alm.

		annotation SummarizationSetBy = Automatic

	column CONTENEDOR
		dataType: string
		lineageTag: 0dda38b1-ebeb-457d-a6f5-f682d8789b35
		summarizeBy: none
		sourceColumn: CONTENEDOR

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 8eeaf35b-da56-4cbd-959a-04fff266a6be
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column 'Nro Expediente'
		dataType: string
		lineageTag: 108a4430-2479-4873-8199-d80c5467d4ad
		summarizeBy: none
		sourceColumn: Nro Expediente

		annotation SummarizationSetBy = Automatic

	column EKPO-FECHA_EXP
		dataType: string
		lineageTag: ed79cfef-e6b8-45d2-9d63-7176f90c84f5
		summarizeBy: none
		sourceColumn: EKPO-FECHA_EXP

		annotation SummarizationSetBy = Automatic

	column EKPO-FECHA_LIQ
		dataType: string
		lineageTag: 6928ee29-ec3a-4a94-a821-b2764ef6dec9
		summarizeBy: none
		sourceColumn: EKPO-FECHA_LIQ

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 85d7a4fb-f718-410d-bea9-64d651c0d97e
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column GCp
		dataType: int64
		formatString: 0
		lineageTag: 7c27128c-b86c-4c57-8e38-2245d4a8708e
		summarizeBy: sum
		sourceColumn: GCp

		annotation SummarizationSetBy = Automatic

	column 'Código EAN/UPC'
		dataType: int64
		formatString: 0
		lineageTag: 37d64476-b6fc-4d30-8690-0c506969f267
		summarizeBy: sum
		sourceColumn: Código EAN/UPC

		annotation SummarizationSetBy = Automatic

	column EFi
		dataType: string
		lineageTag: ff63054a-4f01-4162-a1fc-6138b5e873fc
		summarizeBy: none
		sourceColumn: EFi

		annotation SummarizationSetBy = Automatic

	column CATEGORIA = RELATED(IH09[Desc. Clase])
		lineageTag: 0259c898-1642-44e6-bc92-212ffd8515d4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column KEY = 'TRANS TDAS'[MARCA BV]&'TRANS TDAS'[Ps]&'TRANS TDAS'[Departamento]&'TRANS TDAS'[Genero]&'TRANS TDAS'[CATEGORIA]
		lineageTag: fb550cde-dd0e-42cf-897d-9e40fe7fcd50
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'VALOR PROMEDIO $' =
			
			CALCULATE(
			    AVERAGE('INV ACTUAL'[VALOR $ PROMEDIO]),
			    FILTER(
			        'INV ACTUAL',
			        'INV ACTUAL'[KEY] = EARLIER('TRANS TDAS'[KEY]) &&
			        'INV ACTUAL'[COD ALMACEN] = "AL01"
			    )
			)
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: ec29f242-0e4a-4bfc-a9c6-711cac832ab8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-SV"}

	column 'PARES TRANSITO' = 'TRANS TDAS'[Cantidad solicitada]-'TRANS TDAS'[Cantidad en tiendas]
		lineageTag: 8e377458-5318-4de8-9993-36774dac75d6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'INV TRANS $' = 'TRANS TDAS'[PARES TRANSITO]*'TRANS TDAS'[VALOR PROMEDIO $]
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 5560b3ba-d255-4f75-b9fb-ec7268cc3268
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-SV"}

	column 'TIPO ESTILO' = RELATED(IH09[TIPOESTILO])
		lineageTag: 3931ca7c-d4af-4ae4-9bbc-b707bb8eb8dd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'MARCA BV' = IF(LOOKUPVALUE('MARCAS UNIDAD'[UNIDAD NEGOCIO],'MARCAS UNIDAD'[MARCA BV],'TRANS TDAS'[Marca])="PAR2","PAR2",'TRANS TDAS'[Marca])
		lineageTag: 2379e509-c9da-4af3-b813-8cfced517f7d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column GENERICO = LEFT('TRANS TDAS'[Artículo],8)
		lineageTag: 842651c6-a6fd-4a2b-8038-51592bd2a05f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ' Pos.'
		dataType: int64
		formatString: 0
		lineageTag: 32b7ae6b-76da-407e-b010-56ecc4e6ee9f
		summarizeBy: sum
		sourceColumn: " Pos."

		annotation SummarizationSetBy = Automatic

	column 'Cantidad solicitada'
		dataType: int64
		formatString: 0
		lineageTag: 3efe1b23-6458-45df-97e5-2f1e386da749
		summarizeBy: sum
		sourceColumn: Cantidad solicitada

		annotation SummarizationSetBy = Automatic

	column 'Cantidad confirmada'
		dataType: int64
		formatString: 0
		lineageTag: 75cb441a-d347-40e5-9899-3989af6b2f03
		summarizeBy: sum
		sourceColumn: Cantidad confirmada

		annotation SummarizationSetBy = Automatic

	column 'Cantidad preparada'
		dataType: int64
		formatString: 0
		lineageTag: ec4c9966-00a8-4f71-ba14-5c3aaa17039f
		summarizeBy: sum
		sourceColumn: Cantidad preparada

		annotation SummarizationSetBy = Automatic

	column 'Cantidad en tiendas'
		dataType: int64
		formatString: 0
		lineageTag: e5c4e2b7-2cb2-43c1-a23e-61aa2529df12
		summarizeBy: sum
		sourceColumn: Cantidad en tiendas

		annotation SummarizationSetBy = Automatic

	column fecha_documento
		dataType: string
		lineageTag: 5795dab9-30f3-4e3e-aff4-5a461c05da15
		summarizeBy: none
		sourceColumn: fecha_documento

		annotation SummarizationSetBy = Automatic

	column indicador_de_liquidacion
		dataType: string
		lineageTag: c5097a67-2a16-43c6-83b8-464345471117
		summarizeBy: none
		sourceColumn: indicador_de_liquidacion

		annotation SummarizationSetBy = Automatic

	column CANTIDADREPARTO_TOTAL
		dataType: double
		lineageTag: ae130243-47a4-41a9-8175-82e468b1d3d8
		summarizeBy: sum
		sourceColumn: CANTIDADREPARTO_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PE = RELATED(IH09[PE])
		lineageTag: d2baae12-dfee-4571-bcb9-13f3c22c95ba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'TRANS TDAS' = m
		mode: import
		queryGroup: 'Server SAP (HANA)'
		source =
				let
				    #"EMPUJES" = Value.NativeQuery(SapHana.Database("vhadoahpdb01.hec.empresasadoc.com:30215", [Implementation="2.0"]), "-- DATA CD - TIENDA -#(lf)SELECT #(lf)       EKPO.EBELN                 ""Doc.compr."",  #(lf)       EKPO.EBELP                 "" Pos."",  #(lf)       EKPO.MATNR                 ""Artículo"",  #(lf)       EKPO.MENGE                 ""Cantidad solicitada"",  #(lf)       EKPO.MEINS                 ""UMP"",  #(lf)       EKET.GLMNG                 ""Cantidad confirmada"",  #(lf)       EKET.WAMNG                 ""Cantidad preparada"",  #(lf)       EKET.WEMNG                 ""Cantidad en tiendas"",  #(lf)       EKKO.BSART                 ""Cl."",  #(lf)       EKKO.AEDAT                 ""Creado el"",  #(lf)       EKKO.ERNAM                 ""Creado por"",  #(lf)       EKKO.RESWK                 ""CeSu"",  #(lf)       EKPO.TXZ01                 ""Texto breve"",  #(lf)       EKPO.WERKS                 ""Ce."",  #(lf)       MARA.MTART                 ""TpMt"",  #(lf)       MARA.GROES                 ""Denom. Estilo"",  #(lf)       MARA.SATNR                 ""Mat.gral.conf."",  #(lf)       MARA.FREE_CHAR             ""Color"",  #(lf)       MARA.SIZE1                 ""Tam.1"",  #(lf)       MARA.BRAND_ID              ""Marca"",  #(lf)       MARA.ZZ_ART_PROV           ""Genero"",  #(lf)       T001W.NAME1                ""Nombre 1"",  #(lf)       T001W.LAND1                ""Ps"",  #(lf)       EKPO.LOEKZ                 B,  #(lf)       MARA.ZZ_DEPART             ""Departamento"",  #(lf)       EKKO.ZZ_TIPO_FLETE         ""Caráct.01"",  #(lf)       EKKO.VERKF                 ""Vendedor/a"",  #(lf)       EKPO.RESLO                 ""AlmEmi"",  #(lf)       EKPO.LGORT                 ""Alm."",  #(lf)       ZMM_EXPED_CONTS.CONTENEDOR CONTENEDOR,  #(lf)       EKKO.ZZF_DESPACHO          ""Fecha"",  #(lf)       EKPO.LBELN                 ""Nro Expediente"",  -- Se mantiene solo EKPO.LBELN  #(lf)       EKPO.FECHA_EXP             ""EKPO-FECHA_EXP"",  #(lf)       EKPO.FECHA_LIQ             ""EKPO-FECHA_LIQ"",  #(lf)       EKET.CHARG                 ""Lote"",  #(lf)       EKKO.BEDAT                 ""fecha_documento"",  #(lf)       EKKO.EKGRP                 ""GCp"",  #(lf)       MARA.EAN11                 ""Código EAN/UPC"",  #(lf)       EKKO.FRGKE                 ""indicador_de_liquidacion"",  #(lf)       EKPO.ELIKZ                 ""EFi"",  #(lf)       CASE  #(lf)            WHEN LEFT(EKPO.TXZ01, 7) = 'Prepack'  #(lf)            THEN CAST(SUBSTRING_REGEXPR('(\d+)' IN EKPO.TXZ01 GROUP 1) AS INTEGER)  #(lf)            ELSE 1  #(lf)     END * EKPO.MENGE             CantidadReparto_total  #(lf)FROM SAP_ECC.EKPO  #(lf)LEFT JOIN SAP_ECC.EKKO  #(lf)       ON EKPO.EBELN = EKKO.EBELN  #(lf)LEFT OUTER JOIN SAP_ECC.ZMM_EXPED_CONTS#(lf)       ON ZMM_EXPED_CONTS.LBELN = EKPO.LBELN       #(lf)LEFT JOIN SAP_ECC.EKET  #(lf)       ON EKET.EBELN = EKPO.EBELN  #(lf)          AND EKET.EBELP = EKPO.EBELP  #(lf)LEFT JOIN SAP_ECC.MARA  #(lf)       ON MARA.MATNR = EKPO.MATNR  #(lf)LEFT JOIN SAP_ECC.T001W  #(lf)       ON T001W.WERKS = EKPO.WERKS  #(lf)WHERE  #(lf)    EKKO.AEDAT BETWEEN TO_VARCHAR(TO_DATE(YEAR(CURRENT_DATE) || '0101'), 'YYYYMMDD')#(lf)                  AND TO_VARCHAR(CURRENT_DATE, 'YYYYMMDD')#(lf)    AND EKPO.LOEKZ <> 'L'  #(lf)    AND MARA.MTART IN ('MODE', 'ZMOD')  #(lf)    AND EKKO.BSART IN ('ZTR2', 'ZREP', 'UB','ZTRA')  #(lf)    --AND EKKO.RESWK IN ('8010', '8020', '1010', '1020','2010', '3010', '3030', '4010', '5010', '5030')  #(lf)    --AND EKPO.EBELN = '4801848166'  #(lf)    AND EKPO.MEINS <> 'CS'#(lf)    --AND EKPO.MATNR IN ('000000030073967001')", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(EMPUJES,{{"Doc.compr.", Int64.Type}, {" Pos.", Int64.Type}, {"Artículo", Int64.Type}, {"Cantidad solicitada", Int64.Type}, {"UMP", type text}, {"Cantidad confirmada", Int64.Type}, {"Cantidad preparada", Int64.Type}, {"Cantidad en tiendas", Int64.Type}, {"Cl.", type text}, {"Creado el", type date}, {"Creado por", type text}, {"CeSu", Int64.Type}, {"Texto breve", type text}, {"Ce.", Int64.Type}, {"TpMt", type text}, {"Denom. Estilo", type text}, {"Mat.gral.conf.", Int64.Type}, {"Color", type text}, {"Tam.1", type text}, {"Marca", type text}, {"Genero", type text}, {"Nombre 1", type text}, {"Ps", type text}, {"B", type text}, {"Departamento", type text}, {"Caráct.01", type any}, {"Vendedor/a", type any}, {"AlmEmi", type text}, {"Alm.", type text}, {"CONTENEDOR", type any}, {"Fecha", type text}, {"Nro Expediente", type any}, {"EKPO-FECHA_EXP", type text}, {"EKPO-FECHA_LIQ", type text}, {"Lote", type any}, {"GCp", Int64.Type}, {"Código EAN/UPC", Int64.Type}, {"EFi", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

