table 'Index Oficial'
	lineageTag: 750d4074-460d-4625-bd66-edc0b21ea4f4

	column PERIODO
		dataType: dateTime
		formatString: General Date
		lineageTag: e1777abf-4f4b-44dd-bc95-fd3075a4558b
		summarizeBy: none
		sourceColumn: PERIODO

		annotation SummarizationSetBy = Automatic

	column FECHA = DATE('Index Oficial'[AÑO],'Index Oficial'[MES],'Index Oficial'[COD DIA MES])
		formatString: d mmm yyyy
		lineageTag: 7548b40d-5688-48a9-bdc7-5716209f92ea
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column AÑO
		dataType: string
		lineageTag: 443e0730-0281-492c-8b1c-6a75b75ff24e
		summarizeBy: none
		sourceColumn: AÑO

		annotation SummarizationSetBy = Automatic

	column 'VENTA PLAN $'
		dataType: double
		lineageTag: 1b777980-d08a-447f-8b82-8295c323ac66
		summarizeBy: sum
		sourceColumn: VENTA PLAN $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MARGEN PLAN $'
		dataType: double
		lineageTag: 23f4493b-0e62-4e77-8447-22c1e181c10a
		summarizeBy: sum
		sourceColumn: MARGEN PLAN $

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PAIS BV'
		dataType: string
		lineageTag: 7108e525-01ff-4d6d-acc3-84de14f483d5
		summarizeBy: none
		sourceColumn: PAIS BV

		annotation SummarizationSetBy = Automatic

	column MES
		dataType: string
		lineageTag: af720b3e-03ef-49e3-bc48-9836b546b4f2
		summarizeBy: none
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column 'COD DIA MES'
		dataType: string
		lineageTag: fa53e2bb-bd96-4974-8de5-be4e20764754
		summarizeBy: none
		sourceColumn: COD DIA MES

		annotation SummarizationSetBy = Automatic

	column 'COD DIA SEMANA'
		dataType: string
		lineageTag: 668c9e83-e9aa-4a30-8100-e9961553131c
		summarizeBy: none
		sourceColumn: COD DIA SEMANA

		annotation SummarizationSetBy = Automatic

	column 'DIVISION BV'
		dataType: string
		lineageTag: b923c38b-51ba-4674-9879-e125c83260f1
		summarizeBy: none
		sourceColumn: DIVISION BV

		annotation SummarizationSetBy = Automatic

	column 'AÑO ACTUAL'
		dataType: int64
		formatString: 0
		lineageTag: 9e055c68-90fd-4272-b0c4-00fffa69f58b
		summarizeBy: sum
		sourceColumn: AÑO ACTUAL

		annotation SummarizationSetBy = Automatic

	column 'MES ACTUAL'
		dataType: int64
		formatString: 0
		lineageTag: 59f0a7dd-df3a-4810-8fd9-c53a78133c6c
		summarizeBy: sum
		sourceColumn: MES ACTUAL

		annotation SummarizationSetBy = Automatic

	column NM
		dataType: int64
		formatString: 0
		lineageTag: 46760816-58cc-4fc3-ad6a-1ec99b58475d
		summarizeBy: sum
		sourceColumn: NM

		annotation SummarizationSetBy = Automatic

	column 'AÑO NM'
		dataType: int64
		formatString: 0
		lineageTag: d69b32bd-f4be-4bf2-a58a-3e8576042ebd
		summarizeBy: sum
		sourceColumn: AÑO NM

		annotation SummarizationSetBy = Automatic

	column 'INDEX VTA'
		dataType: double
		lineageTag: ae2e2e93-48cd-45e8-8348-0e57025d2c46
		summarizeBy: sum
		sourceColumn: INDEX VTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'INDEX MG'
		dataType: double
		lineageTag: 17520ce1-ae5c-4123-b7ff-dde10d57fa65
		summarizeBy: sum
		sourceColumn: INDEX MG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Index Oficial' = m
		mode: import
		source =
				let
				    Source = Sql.Database("192.168.16.74", "DM_COMERCIAL", [Query="--INDEX--#(lf)#(lf)WITH Union17 AS (#(lf)    -- first subquery#(lf)    SELECT #(lf)        SUM(FPV1.PLAN_VENTA) AS VENTA_PLAN__,#(lf)        SUM(FPV1.PLAN_MARGEN) AS MARGEN_PLAN__,#(lf)        P.BV_PAIS AS PAIS_BV,#(lf)        PE.PERIODO,#(lf)        PE.ANO AS AÑO,#(lf)        PE.COD_MES,#(lf)        PE.COD_DIA_MES,#(lf)        PE.COD_DIA_SEMANA,#(lf)        A.BV_DIVISION AS DIVISION_BV,#(lf)        YEAR(GETDATE()) AS AÑO_ACTUAL,#(lf)        MONTH(GETDATE()) AS MES_ACTUAL,#(lf)        MONTH(DATEADD(MONTH, 1, GETDATE())) AS NM,#(lf)        YEAR(DATEADD(MONTH, 1, GETDATE())) AS AÑO_NM,#(lf)        SUM(FPV1.PLAN_VENTA) * 1.0 / NULLIF(SUM(SUM(FPV1.PLAN_VENTA)) OVER (PARTITION BY PE.COD_MES, P.BV_PAIS), 0) AS INDEX_VTA,#(lf)        SUM(FPV1.PLAN_MARGEN) * 1.0 / NULLIF(SUM(SUM(FPV1.PLAN_MARGEN)) OVER (PARTITION BY PE.COD_MES, P.BV_PAIS), 0) AS INDEX_MG#(lf)    FROM #(lf)        DM_COMERCIAL.dbo.FAC_PLANVENTA FPV1#(lf)        JOIN DM_COMERCIAL.dbo.DIM_PAIS P ON P.SK_PAIS = FPV1.SK_PAIS#(lf)        JOIN DM_COMERCIAL.dbo.DIM_PERIODO PE ON PE.SK_PERIODO = FPV1.SK_PERIODO#(lf)        JOIN DM_COMERCIAL.dbo.DIM_ALMACEN A ON A.SK_ALMACEN = FPV1.SK_ALMACEN#(lf)        JOIN DM_COMERCIAL.dbo.DIM_TIENDA T ON T.SK_TIENDA = FPV1.SK_TIENDA#(lf)    WHERE #(lf)        PE.ANO = YEAR(GETDATE())#(lf)        AND PE.COD_MES = MONTH(GETDATE())#(lf)        AND A.BV_DIVISION IN ('DET')#(lf)        AND T.TIPO_TIENDA_108 <> 'NN'#(lf)        AND T.SK_TIENDA NOT IN ('0001','0002','0003','0004','0005','0006','0007','0008','0009','0010','0011','0012','0013','0014','0015','0016','0017','0018','0019','0020')#(lf)    GROUP BY #(lf)        P.BV_PAIS, PE.PERIODO, PE.ANO, PE.COD_MES, PE.COD_DIA_MES, PE.COD_DIA_SEMANA,#(lf)        A.BV_DIVISION#(lf)),#(lf)Union_CA AS (#(lf)    -- second subquery#(lf)    SELECT #(lf)        SUM(FPV2.PLAN_VENTA) AS VENTA_PLAN__,#(lf)        SUM(FPV2.PLAN_MARGEN) AS MARGEN_PLAN__,#(lf)        'CA' AS PAIS_BV,#(lf)        PE.PERIODO,#(lf)        PE.ANO AS AÑO,#(lf)        PE.COD_MES,#(lf)        PE.COD_DIA_MES,#(lf)        PE.COD_DIA_SEMANA,#(lf)        A.BV_DIVISION AS DIVISION_BV,#(lf)        YEAR(GETDATE()) AS AÑO_ACTUAL,#(lf)        MONTH(GETDATE()) AS MES_ACTUAL,#(lf)        MONTH(DATEADD(MONTH, 1, GETDATE())) AS NM,#(lf)        YEAR(DATEADD(MONTH, 1, GETDATE())) AS AÑO_NM,#(lf)        SUM(FPV2.PLAN_VENTA) * 1.0 / NULLIF(SUM(SUM(FPV2.PLAN_VENTA)) OVER (PARTITION BY PE.COD_MES), 0) AS INDEX_VTA,#(lf)        SUM(FPV2.PLAN_MARGEN) * 1.0 / NULLIF(SUM(SUM(FPV2.PLAN_MARGEN)) OVER (PARTITION BY PE.COD_MES), 0) AS INDEX_MG#(lf)    FROM #(lf)        DM_COMERCIAL.dbo.FAC_PLANVENTA FPV2#(lf)        JOIN DM_COMERCIAL.dbo.DIM_PERIODO PE ON PE.SK_PERIODO = FPV2.SK_PERIODO#(lf)        JOIN DM_COMERCIAL.dbo.DIM_ALMACEN A ON A.SK_ALMACEN = FPV2.SK_ALMACEN#(lf)        JOIN DM_COMERCIAL.dbo.DIM_TIENDA T ON T.SK_TIENDA = FPV2.SK_TIENDA#(lf)    WHERE #(lf)        PE.ANO = YEAR(GETDATE())#(lf)        AND PE.COD_MES = MONTH(GETDATE())#(lf)        AND A.BV_DIVISION = 'DET'#(lf)        AND T.TIPO_TIENDA_108 <> 'NN'#(lf)        AND T.SK_TIENDA NOT IN ('0001','0002','0003','0004','0005','0006','0007','0008','0009','0010','0011','0012','0013','0014','0015','0016','0017','0018','0019','0020')#(lf)    GROUP BY #(lf)        PE.PERIODO, PE.ANO, PE.COD_MES, PE.COD_DIA_MES, PE.COD_DIA_SEMANA,#(lf)        A.BV_DIVISION#(lf))#(lf)SELECT #(lf)    SUM(U.VENTA_PLAN__) AS VENTA_PLAN__,#(lf)    SUM(U.MARGEN_PLAN__) AS MARGEN_PLAN__,#(lf)    U.PAIS_BV,#(lf)    U.PERIODO,#(lf)    U.AÑO,#(lf)    U.COD_MES,#(lf)    U.COD_DIA_MES,#(lf)    U.COD_DIA_SEMANA,#(lf)    U.DIVISION_BV,#(lf)    U.AÑO_ACTUAL,#(lf)    U.MES_ACTUAL,#(lf)    U.NM,#(lf)    U.AÑO_NM,#(lf)    U.INDEX_VTA,#(lf)    U.INDEX_MG#(lf)FROM (#(lf)    SELECT * FROM Union17#(lf)    UNION ALL#(lf)    SELECT * FROM Union_CA#(lf)) U#(lf)GROUP BY #(lf)    U.PAIS_BV,#(lf)    U.PERIODO,#(lf)    U.AÑO,#(lf)    U.COD_MES,#(lf)    U.COD_DIA_MES,#(lf)    U.COD_DIA_SEMANA,#(lf)    U.DIVISION_BV,#(lf)    U.AÑO_ACTUAL,#(lf)    U.MES_ACTUAL,#(lf)    U.NM,#(lf)    U.AÑO_NM,#(lf)    U.INDEX_VTA,#(lf)    U.INDEX_MG;#(lf)", CreateNavigationProperties=false]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"VENTA_PLAN__", "VENTA PLAN $"}, {"MARGEN_PLAN__", "MARGEN PLAN $"}, {"PAIS_BV", "PAIS BV"}, {"COD_MES", "MES"}, {"COD_DIA_MES", "COD DIA MES"}, {"COD_DIA_SEMANA", "COD DIA SEMANA"}, {"DIVISION_BV", "DIVISION BV"}, {"AÑO_ACTUAL", "AÑO ACTUAL"}, {"MES_ACTUAL", "MES ACTUAL"}, {"AÑO_NM", "AÑO NM"}, {"INDEX_VTA", "INDEX VTA"}, {"INDEX_MG", "INDEX MG"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

