table 'MARCAS UNIDAD'
	lineageTag: a4fc80d6-4d2f-4b5a-9086-81a1dd883958

	column 'MARCA BV'
		dataType: string
		lineageTag: f23c13f6-2d5f-4607-80bb-19fa1c883a40
		summarizeBy: none
		sourceColumn: MARCA BV

		annotation SummarizationSetBy = Automatic

	column 'UNIDAD NEGOCIO'
		dataType: string
		lineageTag: eabed3e5-f95f-44d4-a932-5f970629cbe7
		summarizeBy: none
		sourceColumn: UNIDAD NEGOCIO

		annotation SummarizationSetBy = Automatic

	partition 'MARCAS UNIDAD' = m
		mode: import
		queryGroup: 'Server Dev (20)'
		source =
				let
				    Origen = Sql.Database(srvDev, "ADO_SupplyChain"),
				    dbo_DIM_MARCAS_UNIDAD = Origen{[Schema="dbo",Item="DIM_MARCAS_UNIDAD"]}[Data],
				    #"Columnas con nombre cambiado" = Table.RenameColumns(dbo_DIM_MARCAS_UNIDAD,{{"MARCA_BV", "MARCA BV"}, {"UNIDAD_NEGOCIO", "UNIDAD NEGOCIO"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

