// EVALUATE FILTER(CONTENEDORES , CONTENEDORES[KEY] = "PAR2HNCALMUJTENNIS" ) 

EVALUATE SUMMARIZECOLUMNS(
	CONTENEDORES[EKPO[CONTENEDOR]]],
	FILTER( CONTENEDORES , CONTENEDORES[KEY] = "PAR2HNCALMUJTENNIS" && CONTENEDORES[GENERICO] = "30086228" ),
	"pares", sum( CONTENEDORES[[Pares]]] ),
	"monto", sum( CONTENEDORES[[Monto]]] )
)