table 'Plan Max Año'
	isHidden
	lineageTag: f2894529-a923-43b9-87db-f04c1bdd3559

	column División
		dataType: string
		lineageTag: 555014a3-4685-41e2-8bd2-fb7cbf68e41b
		summarizeBy: none
		sourceColumn: División

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Max Año'
		dataType: int64
		formatString: 0
		lineageTag: 97db8665-c584-494a-9ec1-d4ad9fdb3086
		summarizeBy: sum
		sourceColumn: Max Año

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Plan Max Año-6043e095-4d2d-4d03-ba9c-8496a48364f4' = m
		mode: import
		queryGroup: 'Mapeados\Transformaciones intermedias'
		source =
				let
				    Source = #"Plan Final",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"División", "Año"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Custom1" = Table.AddColumn(#"Removed Duplicates", "Max Año", each List.Max(#"Removed Duplicates"[Año])),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"Año"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Columns"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates1",{{"Max Año", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

