table Métricas
	lineageTag: 6f8fa7ec-9bf5-4b42-8ad8-12760d50e734

	measure 'Precio Un. Local' =
			VAR _flag =
			    ISINSCOPE ( Pais[BV_PAIS] )
			        || ISINSCOPE ( Pais[PAIS] )
			        || HASONEFILTER ( Pais[BV_Pais] )
			        || HASONEFILTER ( Pais[Pais] )
			RETURN
			    IF (
			        _flag,
			        DIVIDE (
			            SUM ( Inventarios[PRECIOT_LOCAL] ),
			            SUM ( Inventarios[PARES] )
			        )
			    )
		formatString: #,0.00
		displayFolder: Precios Unitarios
		lineageTag: 479fa4de-162e-4eb7-a843-38252963cc8e

	measure 'Precio Un. USD' =
			
			DIVIDE (
			    SUM ( Inventarios[PRECIOT_USD] ),
			    SUM ( Inventarios[PARES] )
			)
		formatString: $ #,0.00
		displayFolder: Precios Unitarios
		lineageTag: fac6fed5-fa5f-41be-b107-d21b3ae9cbae

	measure 'Venta Pares' = SUM ( Ventas[Pares] )
		formatString: #,0
		displayFolder: Métrias Comerciales
		lineageTag: bec14efd-4869-4f2d-aada-f90ebbce3679

	measure Venta = SUM ( Ventas[Venta_USD] )
		formatString: $ #,0
		displayFolder: Métrias Comerciales
		lineageTag: 08e82c5d-7722-4cad-9b33-1e7343310b2b

	measure Costo = SUM ( Ventas[Costo_USD] )
		formatString: $ #,0
		displayFolder: Métrias Comerciales
		lineageTag: 40d3e4d7-c577-40cd-96cd-37c2ecb805ff

	measure Margen = [Venta] - [Costo]
		formatString: $ #,0
		displayFolder: Métrias Comerciales
		lineageTag: d3389a1b-83b1-4cd6-9dcc-2d7e41bbaa93

	measure Inventario =
			CALCULATE (
			    SUM ( Inventarios[PARES] ),
			    KEEPFILTERS ( Inventarios[SK_TIPOOPERACION] = "Inventario" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario
		lineageTag: 239f138e-6b68-4c44-998e-94e1976a2b6d

	measure 'Inventario Sala' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario
		lineageTag: e111abad-461e-4ef4-a0e3-048222aa445a

	measure 'Inventario Bodega' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] <> "AL01" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario
		lineageTag: d58f612e-1fd9-4ecb-bbd1-705188a4e06f

	measure 'Inventario Transitos' =
			CALCULATE (
			    SUM ( Inventarios[PARES] ),
			    KEEPFILTERS ( Inventarios[SK_TIPOOPERACION] <> "Inventario" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario
		lineageTag: 94a71c72-1f9a-4b8d-88a0-3c7b957ae090

	measure 'Costo Un. USD' =
			
			DIVIDE (
			    SUM ( Inventarios[COSTOT_USD] ),
			    SUM ( Inventarios[PARES] )
			)
		formatString: $ #,0.00
		displayFolder: Precios Unitarios
		lineageTag: 7ccf972c-5513-49a3-8bce-d1932ceecec8

	measure 'Margen Un. USD' =
			DIVIDE (
			    [Precio Un. USD] - [Costo Un. USD],
			    [Precio Un. USD]
			)
		formatString: #,0.0 %
		displayFolder: Precios Unitarios
		lineageTag: 63f7da9e-910d-44ad-a862-d9b6a985c9c6

	measure Arribos =
			CALCULATE (
			    SUM ( ArriboFuturo[ARRIBO_PARES_ULTIMO_DIA] )
			)
		formatString: #,0
		displayFolder: Métricas Inventario
		lineageTag: b2733531-fdb0-480e-8f8c-1f014c69f1a9

	measure 'Sell Out' = DIVIDE ( [Venta Pares], [Inventario] + [Venta Pares] )
		formatString: #,0.0 %
		displayFolder: Precios Unitarios
		lineageTag: adaa1382-f6ef-4cf9-acbf-375220042c61

	measure 'Margen Un %' = DIVIDE ( [Precio Un. USD] - [Costo Un. USD], [Precio Un. USD] )
		displayFolder: Precios Unitarios
		lineageTag: aba57252-e843-44e1-a0c4-b2b33e4c3367

	measure FOB = AVERAGE ( Precio_FOB[PRECIO_FOB] )
		formatString: $ #,0.00
		displayFolder: Precios Unitarios
		lineageTag: 641cc4f4-0390-4120-a044-78b937d6d6b2

	measure 'F.I.' = DIVIDE ( [Costo Un. USD], AVERAGE ( Precio_FOB[PRECIO_FOB] ) )
		formatString: $ #,0.00
		displayFolder: Precios Unitarios
		lineageTag: dd853a41-1c2b-4e7b-9826-50357d3865fa

	measure 'Precio CA' =
			CALCULATE (
			    [Precio Un. USD],
			    REMOVEFILTERS ( Fecha ),
			    REMOVEFILTERS ( Pais )
			)
		formatString: $ #,0.00
		displayFolder: Precios Unitarios
		lineageTag: cb840147-984e-4f15-9cae-6bb99fe85a5d

	measure 'Costo CA' =
			CALCULATE (
			    [Costo Un. USD],
			    REMOVEFILTERS ( Fecha ),
			    REMOVEFILTERS ( Pais )
			)
		formatString: $ #,0.00
		displayFolder: Precios Unitarios
		lineageTag: dd9fdb9b-1f67-4f82-a16a-a5f7c9aecadc

	measure 'Margen CA' =
			CALCULATE (
			    [Margen Un. USD],
			    REMOVEFILTERS ( Fecha ),
			    REMOVEFILTERS ( Pais )
			)
		formatString: #,0.00 %
		displayFolder: Precios Unitarios
		lineageTag: 5a0e6e0a-debe-4357-aeb4-2c04f3ce305d

	measure 'Venta Mes Actual' = CALCULATE ( [Venta], KEEPFILTERS ( Fecha[Offset] = 0 ) )
		formatString: $ #,0
		displayFolder: Métrias Comerciales\Mes Actual
		lineageTag: fc14f292-f619-4895-a549-5999797c2c0f

	measure 'Pares Mes Actual' = CALCULATE ( [Venta Pares], KEEPFILTERS ( Fecha[Offset] = 0 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Mes Actual
		lineageTag: 1486d80f-89d9-4432-adf9-b1673d48ba07

	measure 'Margen Mes Actual ' = CALCULATE ( [Margen], KEEPFILTERS ( Fecha[Offset] = 0 ) )
		formatString: $ #,0
		displayFolder: Métrias Comerciales\Mes Actual
		lineageTag: fc0768d6-f3f6-462c-ad6c-fefe575d8aad

	measure vEne = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 1 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: ee22ffc7-4d30-45c8-98b8-73eb4a6c5695

	measure vFeb = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 2 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 5cc5edbc-cd31-4e8f-ac2c-52e5b4ffa295

	measure vSep = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 9 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 73033459-0c6b-4c60-ac3a-2e637ea80b5a

	measure vNov = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 11 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 4e05f425-81a6-43ee-9eec-f00409424ff5

	measure vDic = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 12 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 1738b969-bf18-46fe-ad71-b3eccb6dbf57

	measure vOct = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 10 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 2dfb6319-20f7-48eb-a3a8-3e061d9f6516

	measure vAgo = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 8 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 50b36ae7-338f-44ee-a119-d7404f323adb

	measure vJul = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 7 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 442b9a48-56eb-46f9-9ff9-028c64fb828b

	measure vJun = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 6 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 80c48e27-c4bb-49e8-a138-e44a149ca6a6

	measure vMar = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 3 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: 2aa6f1a4-e7d4-435f-9d23-13cc963c5ae4

	measure vAbr = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 4 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: ce160e76-9bca-49a3-8c5e-793d8a2b75af

	measure vMay = CALCULATE ( [Venta Pares], KEEPFILTERS ( 'Fecha'[Num. Mes] = 5 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Pares Mensual
		lineageTag: b7414f31-8cf3-4e67-ba9f-9f8d4d660296

	measure aAbr = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 4 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: cb15b7b4-23f4-4dbc-bdd8-6b1732478bc6

	measure aAgo = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 8 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 2b85d24e-241e-4b5b-aeac-d65b2fefb72e

	measure aDic = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 12 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: ad12bd7b-299b-4e22-adc1-dd2d680beed1

	measure aEne = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 1 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 73f2aceb-e772-411d-8a69-2159f3c2116b

	measure aFeb = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 2 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 6b7ad8c6-3bb0-4a1c-8000-7acc11c0b0f2

	measure aJul = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 7 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: a41e1c67-19fa-45b1-8250-84e0ed368f37

	measure aJun = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 6 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: c2036b08-aa02-4643-8bcc-6f4e853959ad

	measure aMar = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 3 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: e84d8af5-8dba-4b73-a4c0-88eac6715fb3

	measure aMay = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 5 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 8f98ab58-20d0-446c-8df8-26162ae6b62f

	measure aNov = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 11 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 2d4d9e8b-fe7d-42ca-b5ef-f790b735de11

	measure aOct = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 10 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 9954a84b-214a-4608-b1ac-322d7711941d

	measure aSep = CALCULATE ( [Arribos], KEEPFILTERS ( 'Fecha'[Num. Mes] = 9 ) )
		formatString: #,0
		displayFolder: Métrias Comerciales\Arribos Mensual
		lineageTag: 33b833e3-7c62-4899-a58c-b31143095240

	measure 'Meses con Venta' =
			CALCULATE (
			    DISTINCTCOUNT ( Fecha[NumAnoMes] ),
			    Fecha[Fecha] IN VALUES ( Ventas[Fecha] )
			)
		formatString: #,0
		displayFolder: Métrias Comerciales
		lineageTag: d2658bac-57df-4ebb-a4bf-098869ad7105

	measure Cobertura =
			DIVIDE (
			    [Inventario],
			    DIVIDE (
			        [Venta Pares],
			        [Meses con Venta]
			    )
			)
		formatString: #,0.0
		displayFolder: Métricas Inventario
		lineageTag: 2d61f12b-44c2-4c0f-ad27-3364af57eee6

	measure 'Sell Out Anual' =
			DIVIDE (
			    [Venta Pares],
			    [Inventario] + [Arribos]
			)
		formatString: #,0.0 %
		displayFolder: Precios Unitarios
		lineageTag: 7483690e-181d-4e7f-a908-c0f46385cc23

	measure 'Venta Pares Prom.' = DIVIDE ( [Venta Pares] , [Meses con Venta] )
		formatString: #,0
		displayFolder: Métrias Comerciales
		lineageTag: b307bc02-8ca5-462d-8df4-4f3aafaf4dbc

	measure EOSS =
			-- FROM PROMOS PRISM
			-- IF ( NOT ISBLANK ( COUNTROWS ( PROMOS ) ), "X" )
			IF (
			    SELECTEDVALUE ( 'Articulos'[SK_ESTATUS] ) IN { "2", "3", "4" },
			    "X"
			)
		displayFolder: Métrias Comerciales
		lineageTag: f3158caf-1a90-4aeb-971d-1534f27acc74

	measure 'Inventario BP10' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "BP10" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas
		lineageTag: 902df04b-a4ca-4786-a288-0bf232f61f27

	measure 'Inventario BFI' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS ( CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" ) )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas
		lineageTag: 3ea05e2c-6dac-415d-8e6d-79f07c0994e9

	measure 'Inventario Otras Bodegas' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS (
			        NOT CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" )
			            && NOT Almacenes[SK_ALMACEN] = "BP10"
			    )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas
		lineageTag: 221cc14e-5cc7-487e-ae5d-43f578dbba6f

	measure 'Cod Prov.' =
			CALCULATE (
			    SELECTEDVALUE (
			        'ArriboFuturo'[COD-PRO]
			    )
			)
		displayFolder: Métricas Inventario
		lineageTag: 9d519818-79e5-40f6-83e6-5da5800a50fb

	measure 'Nom Prov.' =
			CALCULATE (
			    SELECTEDVALUE (
			        'ArriboFuturo'[NOPRMP]
			    )
			)
		displayFolder: Métricas Inventario
		lineageTag: ed029117-f810-44d0-80b7-ecac5ddee64c

	measure 'PV $' =
			VAR _flag =
			    ISINSCOPE ( Pais[BV_PAIS] )
			        || ISINSCOPE ( Pais[PAIS] )
			        || HASONEFILTER ( Pais[BV_Pais] )
			        || HASONEFILTER ( Pais[Pais] )
			RETURN
			    IF (
			        _flag,
			        [Precio Un. USD]
			    )
		formatString: #,0.00
		displayFolder: Precios Unitarios
		lineageTag: 73676980-736e-4ede-8219-1ee435d6c1ab

	measure 'Inventario 8010' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS ( CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" ) ),
			    KEEPFILTERS ( Inventarios[SK_Tienda] = "8010" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\BFI
		lineageTag: 328b5fcd-4c3d-41ad-a0ab-a9f0970464af

	measure 'Inventario 8020' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS ( CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" ) ),
			    KEEPFILTERS ( Inventarios[SK_Tienda] = "8020" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\BFI
		lineageTag: 1ad55c16-52d8-4b3d-b687-e364efce86d7

	measure 'Inventario PA20' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS ( CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" ) ),
			    KEEPFILTERS ( Inventarios[SK_Tienda] = "PA20" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\BFI
		lineageTag: bdcfca49-9397-4d47-bb07-679d0db0fa3f

	measure 'Inventario Bodegas SV' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS (
			        NOT CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" )
			            && NOT Almacenes[SK_ALMACEN] = "BP10"
			    ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "SV" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\Bodegas
		lineageTag: 548bb013-f4b9-4202-b2b5-858f8f401039

	measure 'Inventario Bodegas GT' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS (
			        NOT CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" )
			            && NOT Almacenes[SK_ALMACEN] = "BP10"
			    ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "GT" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\Bodegas
		lineageTag: 0f4e0b82-5791-4559-9bf4-6e77b612d992

	measure 'Inventario Bodegas CR' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS (
			        NOT CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" )
			            && NOT Almacenes[SK_ALMACEN] = "BP10"
			    ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "CR" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\Bodegas
		lineageTag: 61329ca2-4b50-4665-8758-bb5dbc68a417

	measure 'Inventario Bodegas HN' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS (
			        NOT CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" )
			            && NOT Almacenes[SK_ALMACEN] = "BP10"
			    ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "HN" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\Bodegas
		lineageTag: 67406284-6841-4064-aa73-4ff58c43dcd2

	measure 'Inventario Bodegas NI' =
			CALCULATE (
			    [Inventario Bodega],
			    KEEPFILTERS (
			        NOT CONTAINSSTRING ( Almacenes[SK_ALMACEN], "BF" )
			            && NOT Almacenes[SK_ALMACEN] = "BP10"
			    ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "NI" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\Inventario Bodegas\Bodegas
		lineageTag: 0b3629cf-7497-422c-8718-70c61fdb0d34

	measure 'Ex. TDA SV' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "SV" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\TDA Paises
		lineageTag: efb79131-8294-489b-b322-1c93d7e5f8fa

	measure 'Ex. TDA GT' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "GT" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\TDA Paises
		lineageTag: 75386ec2-b873-4e5c-8872-81abc19764d8

	measure 'Ex. TDA HN' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "HN" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\TDA Paises
		lineageTag: b26f909d-b3cd-4252-879b-bcc823777458

	measure 'Ex. TDA NI' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "NI" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\TDA Paises
		lineageTag: 0a6ad777-7a93-4b82-92b4-59510528d774

	measure 'Ex. TDA CR' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "CR" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\TDA Paises
		lineageTag: 6fffc402-ad84-4ebe-8257-68765e5137f0

	measure 'Ex. TDA PA' =
			CALCULATE (
			    [Inventario],
			    KEEPFILTERS ( Almacenes[SK_ALMACEN] = "AL01" ),
			    KEEPFILTERS ( Pais[BV_PAIS] = "PA" )
			)
		formatString: #,0
		displayFolder: Métricas Inventario\TDA Paises
		lineageTag: df650599-bd63-48d5-9a65-23bc41c70a85

	measure 'Primera Fecha' = SELECTEDVALUE ( ArticulosPais[PrimeraFecha] )
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas
		lineageTag: c262cd6b-b04d-44ad-a889-bbfc82ce8016

	measure 'Ultima Fecha' = SELECTEDVALUE ( ArticulosPais[PrimeraFecha] )
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas
		lineageTag: 1edd48fe-bc65-46f2-abbe-7f89891592c0

	measure 'Primera Fecha SV' =
			CALCULATE (
			    [Primera Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "SV" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 6c86ee52-65ee-486a-a94e-56b603229fd9

	measure 'Ultima Fecha SV' =
			CALCULATE (
			    [Ultima Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "SV" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: cfcb84b0-6718-4f2e-a219-bf23205e51c8

	measure 'Primera Fecha HN' =
			CALCULATE (
			    [Primera Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "HN" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 563b5538-f353-4ff3-ad9f-f8ab06ab78af

	measure 'Ultima Fecha HN' =
			CALCULATE (
			    [Ultima Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "HN" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: d49843f9-3789-41b4-a286-f8bc582d8e06

	measure 'Primera Fecha NI' =
			CALCULATE (
			    [Primera Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "NI" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 31af4231-b297-4f4b-b892-c2d63d8155e2

	measure 'Ultima Fecha NI' =
			CALCULATE (
			    [Ultima Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "NI" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 500f8ae7-91b6-4d4c-a4f1-c130f40d642b

	measure 'Primera Fecha GT' =
			CALCULATE (
			    [Primera Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "GT" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 3afaaf53-7b31-4249-b3fa-c01ee9a07cbb

	measure 'Ultima Fecha GT' =
			CALCULATE (
			    [Ultima Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "GT" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: fdba7cf2-6410-4758-840f-68dd0930f1df

	measure 'Primera Fecha CR' =
			CALCULATE (
			    [Primera Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "CR" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: a616f986-0bda-466f-9cfc-fca2f7d23dd7

	measure 'Ultima Fecha CR' =
			CALCULATE (
			    [Ultima Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "CR" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 12a44cd3-206a-49d7-bb1c-9c1b053e3876

	measure 'Primera Fecha PA' =
			CALCULATE (
			    [Primera Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "PA" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 60fdc352-270a-44a7-8fec-844dc2f11e15

	measure 'Ultima Fecha PA' =
			CALCULATE (
			    [Ultima Fecha],
			    KEEPFILTERS ( Pais[BV_Pais] = "PA" )
			)
		formatString: yyyy-MM-dd
		displayFolder: Métrias Comerciales\Fechas\Paises
		lineageTag: 694b9afd-e7ee-4d6d-a214-cd31ecbf55d9

	measure 'Precio IVA SV' =
			VAR _art =
			    SELECTEDVALUE ( Articulos[SK_ARTICULO] )
			VAR _pais =
			    SELECTEDVALUE ( Pais[SK_PAIS] )
			VAR _val =
			    CALCULATE (
			        MAX ( ArticuloPrecios[PRECIO_IVA] ),
			        REMOVEFILTERS ( ArticulosPais ),
			        ArticuloPrecios[MATNR] = _art,
			        -- ArticuloPrecios[SK_PAIS] = _pais,
			        KEEPFILTERS ( Pais[BV_PAIS] = "SV" )
			    )
			RETURN
			    _val
		formatString: $ #,0.00
		displayFolder: Precios Unitarios\Con IVA
		lineageTag: fab4efd1-4781-4004-8b14-9556cb341710

	measure 'Precio IVA HN' =
			VAR _art =
			    SELECTEDVALUE ( Articulos[SK_ARTICULO] )
			VAR _pais =
			    SELECTEDVALUE ( Pais[SK_PAIS] )
			VAR _val =
			    CALCULATE (
			        MAX ( ArticuloPrecios[PRECIO_IVA] ),
			        REMOVEFILTERS ( ArticulosPais ),
			        ArticuloPrecios[MATNR] = _art,
			        -- ArticuloPrecios[SK_PAIS] = _pais,
			        KEEPFILTERS ( Pais[BV_PAIS] = "HN" )
			    )
			RETURN
			    _val
		formatString: L #,0.00
		displayFolder: Precios Unitarios\Con IVA
		lineageTag: 410b041a-be4d-4676-ab17-8dcc5e1049a1

	measure 'Precio IVA NI' =
			VAR _art =
			    SELECTEDVALUE ( Articulos[SK_ARTICULO] )
			VAR _pais =
			    SELECTEDVALUE ( Pais[SK_PAIS] )
			VAR _val =
			    CALCULATE (
			        MAX ( ArticuloPrecios[PRECIO_IVA] ),
			        REMOVEFILTERS ( ArticulosPais ),
			        ArticuloPrecios[MATNR] = _art,
			        -- ArticuloPrecios[SK_PAIS] = _pais,
			        KEEPFILTERS ( Pais[BV_PAIS] = "NI" )
			    )
			RETURN
			    _val
		formatString: \C #,0.00
		displayFolder: Precios Unitarios\Con IVA
		lineageTag: ac08a822-a82a-48b4-a881-295a8f927282

	measure 'Precio IVA GT' =
			VAR _art =
			    SELECTEDVALUE ( Articulos[SK_ARTICULO] )
			VAR _pais =
			    SELECTEDVALUE ( Pais[SK_PAIS] )
			VAR _val =
			    CALCULATE (
			        MAX ( ArticuloPrecios[PRECIO_IVA] ),
			        REMOVEFILTERS ( ArticulosPais ),
			        ArticuloPrecios[MATNR] = _art,
			        -- ArticuloPrecios[SK_PAIS] = _pais,
			        KEEPFILTERS ( Pais[BV_PAIS] = "GT" )
			    )
			RETURN
			    _val
		formatString: \Q #,0.00
		displayFolder: Precios Unitarios\Con IVA
		lineageTag: 1bd3d469-53e1-41db-b2cf-be1903d22728

	measure 'Precio IVA CR' =
			VAR _art =
			    SELECTEDVALUE ( Articulos[SK_ARTICULO] )
			VAR _pais =
			    SELECTEDVALUE ( Pais[SK_PAIS] )
			VAR _val =
			    CALCULATE (
			        MAX ( ArticuloPrecios[PRECIO_IVA] ),
			        REMOVEFILTERS ( ArticulosPais ),
			        ArticuloPrecios[MATNR] = _art,
			        -- ArticuloPrecios[SK_PAIS] = _pais,
			        KEEPFILTERS ( Pais[BV_PAIS] = "CR" )
			    )
			RETURN
			    _val
		formatString: \C #,0.00
		displayFolder: Precios Unitarios\Con IVA
		lineageTag: 62373255-7278-48cc-920e-908ac8cf32b4

	measure 'Precio IVA PA' =
			VAR _art =
			    SELECTEDVALUE ( Articulos[SK_ARTICULO] )
			VAR _pais =
			    SELECTEDVALUE ( Pais[SK_PAIS] )
			VAR _val =
			    CALCULATE (
			        MAX ( ArticuloPrecios[PRECIO_IVA] ),
			        REMOVEFILTERS ( ArticulosPais ),
			        ArticuloPrecios[MATNR] = _art,
			        -- ArticuloPrecios[SK_PAIS] = _pais,
			        KEEPFILTERS ( Pais[BV_PAIS] = "PA" )
			    )
			RETURN
			    _val
		formatString: $ #,0.00
		displayFolder: Precios Unitarios\Con IVA
		lineageTag: d207d1e7-be95-4b0e-a82c-d41f84839afc

	measure 'Margen %' = DIVIDE ( [Margen] , [Venta] )
		formatString: #,0.00 %
		displayFolder: Métrias Comerciales
		lineageTag: 7e8f9407-2081-492b-9491-e94e5d3acd71

	measure 'Venta %' =
			//VAR _base =
			//    CALCULATE ( [Venta], REMOVEFILTERS ( 'Fecha'[Mes Año] ) )
			//RETURN
			//    DIVIDE ( [Venta], _base )
			VAR _anio =
			    MAX ( Fecha[Año] )
			VAR _flag = ISINSCOPE ( 'Fecha'[Mes Año] )
			VAR _base =
			    CALCULATE (
			        [Venta],
			        REMOVEFILTERS ( Fecha ),
			        KEEPFILTERS ( Fecha[Año] = _anio )
			    ) * DIVIDE ( _flag , _flag )
			RETURN
			    DIVIDE ( [Venta], _base )
		formatString: #,0.00 %
		displayFolder: Métrias Comerciales
		lineageTag: 897a5a5a-9327-4923-aa3e-bd583d7d961b

	measure 'SO %' =
			VAR _lastDate =
			    MAX ( Fecha[Fecha] )
			VAR _paresAcu =
			    CALCULATE ( [Venta Pares], Fecha[Fecha] <= _lastDate )
			VAR _fechas =
			    CALCULATE ( COUNTROWS ( Fecha ) , Fecha[Offset] <= 0 )
			VAR _inv =
			    CALCULATE ( [Inventario], REMOVEFILTERS ( Fecha ) )
			RETURN
			    DIVIDE ( _paresAcu , _inv + _paresAcu ) * DIVIDE ( _fechas, _fechas )
		formatString: #,0.00 %
		displayFolder: Métrias Comerciales
		lineageTag: 459f8e28-55e1-4ea3-87d7-626343a5775e

	measure PPV = ```
			DIVIDE ( [Venta] , [Venta Pares] )
			
			```
		formatString: $ #,0.00
		displayFolder: Métrias Comerciales
		lineageTag: fe2eaa66-2331-4057-941e-188828b52a33

	column Value
		isHidden
		lineageTag: d4fdf9b7-3933-4949-89ba-53aad45b77f3
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'New Calculated Table' = calculated
		mode: import
		source = {BLANK()}

